import 'package:cinemate/constants/assets.dart';
import 'package:cinemate/models/movie_credits_response_model.dart';
import 'package:cinemate/services/process_image_link.dart';
import 'package:flutter/material.dart';

class CastList extends StatelessWidget {
  final int movieId;

  const CastList({super.key, required this.movieId});

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.sizeOf(context).width;
    double height = MediaQuery.sizeOf(context).height;
    final credits = MovieCreditsResponse.fromJson(const {
      'id': 385687,
      'cast': [
        {
          'adult': false,
          'gender': 2,
          'id': 12835,
          'known_for_department': 'Acting',
          'name': 'Vin Diesel',
          'original_name': 'Vin Diesel',
          'popularity': 58.215,
          'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg',
          'cast_id': 0,
          'character': 'Dominic Toretto',
          'credit_id': '56d8c1e0c3a3681e3601fdc6',
          'order': 0
        },
        {
          'adult': false,
          'gender': 1,
          'id': 17647,
          'known_for_department': 'Acting',
          'name': 'Michelle Rodriguez',
          'original_name': 'Michelle Rodriguez',
          'popularity': 26.369,
          'profile_path': '/B3R1Yrdrw9LoCjcQ8CnW7ikgbw.jpg',
          'cast_id': 33,
          'character': 'Letty',
          'credit_id': '6107f6a1ee43e80027c7bea1',
          'order': 1
        },
        {
          'adult': false,
          'gender': 2,
          'id': 8169,
          'known_for_department': 'Acting',
          'name': 'Tyrese Gibson',
          'original_name': 'Tyrese Gibson',
          'popularity': 29.74,
          'profile_path': '/1K315wBQBvDBuZMlzoozuGsqFXZ.jpg',
          'cast_id': 35,
          'character': 'Roman',
          'credit_id': '6107f6d61c635b003010d62b',
          'order': 2
        },
        {
          'adult': false,
          'gender': 2,
          'id': 8171,
          'known_for_department': 'Acting',
          'name': 'Ludacris',
          'original_name': 'Ludacris',
          'popularity': 25.378,
          'profile_path': '/erkJijujhe48vhJ8iCEtVpNEeVn.jpg',
          'cast_id': 36,
          'character': 'Tej',
          'credit_id': '6107f6ec8d22fc004713585b',
          'order': 3
        },
        {
          'adult': false,
          'gender': 2,
          'id': 56446,
          'known_for_department': 'Acting',
          'name': 'John Cena',
          'original_name': 'John Cena',
          'popularity': 33.378,
          'profile_path': '/rgB2eIOt7WyQjdgJCOuESdDlrjg.jpg',
          'cast_id': 70,
          'character': 'Jakob Toretto',
          'credit_id': '62991471a44d095275e980c1',
          'order': 4
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1251069,
          'known_for_department': 'Acting',
          'name': 'Nathalie Emmanuel',
          'original_name': 'Nathalie Emmanuel',
          'popularity': 37.739,
          'profile_path': '/koSwmmonFJiZDfwmZgdVA7I1aR.jpg',
          'cast_id': 37,
          'character': 'Ramsey',
          'credit_id': '6107f70e17c443004690f509',
          'order': 5
        },
        {
          'adult': false,
          'gender': 1,
          'id': 22123,
          'known_for_department': 'Acting',
          'name': 'Jordana Brewster',
          'original_name': 'Jordana Brewster',
          'popularity': 26.269,
          'profile_path': '/8VzFsSfT7NnMGyH5JQBQdTxDHcO.jpg',
          'cast_id': 34,
          'character': 'Mia Toretto',
          'credit_id': '6107f6c08d22fc00300eee15',
          'order': 6
        },
        {
          'adult': false,
          'gender': 2,
          'id': 61697,
          'known_for_department': 'Acting',
          'name': 'Sung Kang',
          'original_name': 'Sung Kang',
          'popularity': 21.941,
          'profile_path': '/jCrjAt7L1SO4TOC0O6Nr7ZZU8vS.jpg',
          'cast_id': 38,
          'character': 'Han',
          'credit_id': '6107f7267ad08c005e578d66',
          'order': 7
        },
        {
          'adult': false,
          'gender': 2,
          'id': 117642,
          'known_for_department': 'Acting',
          'name': 'Jason Momoa',
          'original_name': 'Jason Momoa',
          'popularity': 67.563,
          'profile_path': '/6dEFBpZH8C8OijsynkSajQT99Pb.jpg',
          'cast_id': 56,
          'character': 'Dante',
          'credit_id': '61f42773a6fdaa001c92e6e4',
          'order': 8
        },
        {
          'adult': false,
          'gender': 2,
          'id': 928572,
          'known_for_department': 'Acting',
          'name': 'Scott Eastwood',
          'original_name': 'Scott Eastwood',
          'popularity': 33.029,
          'profile_path': '/w8yZtoTB2XGJWYJxZBLWp1Smqrk.jpg',
          'cast_id': 64,
          'character': 'Little Nobody',
          'credit_id': '6286770c6d9fe85497bfb9d1',
          'order': 9
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1784612,
          'known_for_department': 'Acting',
          'name': 'Daniela Melchior',
          'original_name': 'Daniela Melchior',
          'popularity': 24.453,
          'profile_path': '/iLO8qrSldSTC1omutFiO9oyIz6m.jpg',
          'cast_id': 57,
          'character': 'Isabel',
          'credit_id': '6238f9898ac3d0004430ba9f',
          'order': 10
        },
        {
          'adult': false,
          'gender': 2,
          'id': 64295,
          'known_for_department': 'Acting',
          'name': 'Alan Ritchson',
          'original_name': 'Alan Ritchson',
          'popularity': 50.844,
          'profile_path': '/iV4XpUEsvnncbRv1SJKasRY05cK.jpg',
          'cast_id': 63,
          'character': 'Aimes',
          'credit_id': '627e8b59c92c5d0068aaef0c',
          'order': 11
        },
        {
          'adult': false,
          'gender': 1,
          'id': 15735,
          'known_for_department': 'Acting',
          'name': 'Helen Mirren',
          'original_name': 'Helen Mirren',
          'popularity': 39.48,
          'profile_path': '/1reKRrsdsHXJaRVHVyOEg4oPTcZ.jpg',
          'cast_id': 77,
          'character': 'Queenie',
          'credit_id': '6326a2f943250f007b7e09ae',
          'order': 12
        },
        {
          'adult': false,
          'gender': 1,
          'id': 60073,
          'known_for_department': 'Acting',
          'name': 'Brie Larson',
          'original_name': 'Brie Larson',
          'popularity': 42.168,
          'profile_path': '/wDjAlyUpTrgEzqJK5t9lAz2P3XP.jpg',
          'cast_id': 58,
          'character': 'Tess',
          'credit_id': '625258b0894ed600abc4e21b',
          'order': 13
        },
        {
          'adult': false,
          'gender': 2,
          'id': 976,
          'known_for_department': 'Acting',
          'name': 'Jason Statham',
          'original_name': 'Jason Statham',
          'popularity': 98.719,
          'profile_path': '/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg',
          'cast_id': 74,
          'character': 'Shaw',
          'credit_id': '62ab7a9435a61e0062082a1b',
          'order': 14
        },
        {
          'adult': false,
          'gender': 1,
          'id': 6885,
          'known_for_department': 'Acting',
          'name': 'Charlize Theron',
          'original_name': 'Charlize Theron',
          'popularity': 46.877,
          'profile_path': '/ghVr6dRoaN4n1KRNy91fnvIJUkm.jpg',
          'cast_id': 49,
          'character': 'Cipher',
          'credit_id': '61367fbbef9d72002bee076d',
          'order': 15
        },
        {
          'adult': false,
          'gender': 1,
          'id': 13299,
          'known_for_department': 'Acting',
          'name': 'Rita Moreno',
          'original_name': 'Rita Moreno',
          'popularity': 12.646,
          'profile_path': '/zB0M77jr7tmsmWHEr2bWO2Xq66L.jpg',
          'cast_id': 69,
          'character': 'Abuelita',
          'credit_id': '628ce4ee1a32483b630dbee0',
          'order': 16
        },
        {
          'adult': false,
          'gender': 2,
          'id': 22462,
          'known_for_department': 'Acting',
          'name': 'Joaquim de Almeida',
          'original_name': 'Joaquim de Almeida',
          'popularity': 28.994,
          'profile_path': '/muXJn8kTEPxJaetkgCyS8RPEzTC.jpg',
          'cast_id': 113,
          'character': 'Hernan Reyes',
          'credit_id': '6400bc4e7a4ee700f0fa7144',
          'order': 17
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2984075,
          'known_for_department': 'Acting',
          'name': 'Leo A. Perry',
          'original_name': 'Leo A. Perry',
          'popularity': 2.68,
          'profile_path': '/22yhaD35P2AzJ8nA7EMbuIyyHEw.jpg',
          'cast_id': 81,
          'character': 'Little Brian',
          'credit_id': '63d945729512e1008f378bda',
          'order': 18
        },
        {
          'adult': false,
          'gender': 2,
          'id': 37149,
          'known_for_department': 'Acting',
          'name': 'Luis Da Silva Jr.',
          'original_name': 'Luis Da Silva Jr.',
          'popularity': 8.064,
          'profile_path': '/ajavEvDuNcinuw3BJ80OE0sEU5Q.jpg',
          'cast_id': 79,
          'character': 'Diogo',
          'credit_id': '638663455ed8e900b89eb2b1',
          'order': 19
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1678751,
          'known_for_department': 'Acting',
          'name': 'Jaz Hutchins',
          'original_name': 'Jaz Hutchins',
          'popularity': 1.388,
          'profile_path': '/nvXgXVGOaHjE3HGE53FJQ4jvdww.jpg',
          'cast_id': 139,
          'character': 'Agency Tech',
          'credit_id': '646aba5f57530e078753ead7',
          'order': 20
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1897706,
          'known_for_department': 'Acting',
          'name': 'Luka Hays',
          'original_name': 'Luka Hays',
          'popularity': 1.62,
          'profile_path': null,
          'cast_id': 140,
          'character': 'Cipher Tech',
          'credit_id': '646aba92a5046e018941f2ba',
          'order': 21
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4074147,
          'known_for_department': 'Acting',
          'name': 'Alexander Capon',
          'original_name': 'Alexander Capon',
          'popularity': 1.4,
          'profile_path': null,
          'cast_id': 141,
          'character': 'Cipher Tech',
          'credit_id': '646abab5c3514c00e5dddabb',
          'order': 22
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1427948,
          'known_for_department': 'Acting',
          'name': 'Pete Davidson',
          'original_name': 'Pete Davidson',
          'popularity': 33.018,
          'profile_path': '/mSlLMk45CUgMGT1o7Pkh9zYaLxK.jpg',
          'cast_id': 132,
          'character': 'Bowie',
          'credit_id': '646474d29f37b0017d5814b3',
          'order': 23
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4074148,
          'known_for_department': 'Acting',
          'name': 'Shadrach Agozino',
          'original_name': 'Shadrach Agozino',
          'popularity': 1.4,
          'profile_path': null,
          'cast_id': 142,
          'character': 'Bartender',
          'credit_id': '646abae1d1857201802d7101',
          'order': 24
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2282001,
          'known_for_department': 'Acting',
          'name': 'Ludmilla',
          'original_name': 'Ludmilla',
          'popularity': 1.677,
          'profile_path': '/hbEkg827B38ieLV8ZQZf0f65KET.jpg',
          'cast_id': 115,
          'character': 'Starter',
          'credit_id': '6446ce476dc507051fd4b0b9',
          'order': 25
        },
        {
          'adult': false,
          'gender': 2,
          'id': 508582,
          'known_for_department': 'Acting',
          'name': 'Miraj Grbić',
          'original_name': 'Miraj Grbić',
          'popularity': 1.619,
          'profile_path': '/ptCynXMskQ8CETCvg6ZjSwcMyVI.jpg',
          'cast_id': 270,
          'character': 'Russian Bag Guy',
          'credit_id': '64830e07d2b209014e08312b',
          'order': 26
        },
        {
          'adult': false,
          'gender': 1,
          'id': 3184164,
          'known_for_department': 'Acting',
          'name': 'Meadow Walker Thornton-Allan',
          'original_name': 'Meadow Walker Thornton-Allan',
          'popularity': 1.4,
          'profile_path': '/rjH3yn1r5CdhVClRxNfLkw5gcZZ.jpg',
          'cast_id': 116,
          'character': 'Flight Attendant',
          'credit_id': '6448a7782fdec60573a0cb36',
          'order': 27
        },
        {
          'adult': false,
          'gender': 2,
          'id': 124304,
          'known_for_department': 'Acting',
          'name': 'Michael Irby',
          'original_name': 'Michael Irby',
          'popularity': 6.565,
          'profile_path': '/9cX8pKujyAlOyqGSAgvKNdA3qRj.jpg',
          'cast_id': 269,
          'character': 'Zizi (archive footage)',
          'credit_id': '6483066fbf31f250570578fc',
          'order': 28
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4074151,
          'known_for_department': 'Acting',
          'name': 'Shahir Figueira',
          'original_name': 'Shahir Figueira',
          'popularity': 0.98,
          'profile_path': null,
          'cast_id': 145,
          'character': 'Officer',
          'credit_id': '646abbc82bcf67011bf3ec53',
          'order': 29
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2545367,
          'known_for_department': 'Acting',
          'name': 'Ben-Hur Santos',
          'original_name': 'Ben-Hur Santos',
          'popularity': 1.566,
          'profile_path': '/jjVqqt2e2b4TgBnrjHwYkKpvSBN.jpg',
          'cast_id': 146,
          'character': 'Lead Cartel Thug',
          'credit_id': '646abbdb57530e0788ae51d9',
          'order': 30
        },
        {
          'adult': false,
          'gender': 1,
          'id': 123846,
          'known_for_department': 'Acting',
          'name': 'Debby Ryan',
          'original_name': 'Debby Ryan',
          'popularity': 19.874,
          'profile_path': '/hYMnrAO1fZx9tPmIM8xajliVT1N.jpg',
          'cast_id': 135,
          'character': 'Debby Ryan',
          'credit_id': '64668e1833a3760158d89e32',
          'order': 31
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2138286,
          'known_for_department': 'Acting',
          'name': 'Josh Dun',
          'original_name': 'Josh Dun',
          'popularity': 1.63,
          'profile_path': '/7xT72GgPrkllGjAF4vtyj4J65d1.jpg',
          'cast_id': 136,
          'character': 'Josh Dun',
          'credit_id': '64668e252bcf67011bf209dc',
          'order': 32
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2148372,
          'known_for_department': 'Crew',
          'name': 'Robert Bastens',
          'original_name': 'Robert Bastens',
          'popularity': 1.448,
          'profile_path': null,
          'cast_id': 147,
          'character': 'Dom Stand In',
          'credit_id': '646abc1ea5046e00e5b6e21f',
          'order': 33
        },
        {
          'adult': false,
          'gender': 2,
          'id': 18918,
          'known_for_department': 'Acting',
          'name': 'Dwayne Johnson',
          'original_name': 'Dwayne Johnson',
          'popularity': 32.247,
          'profile_path': '/cgoy7t5Ve075naBPcewZrc08qGw.jpg',
          'cast_id': 117,
          'character': 'Luke Hobbs (uncredited)',
          'credit_id': '645eb09eb234b900fe037c40',
          'order': 34
        },
        {
          'adult': false,
          'gender': 1,
          'id': 90633,
          'known_for_department': 'Acting',
          'name': 'Gal Gadot',
          'original_name': 'Gal Gadot',
          'popularity': 48.576,
          'profile_path': '/plLfB60M5cJrnog8KvAKhI4UJuk.jpg',
          'cast_id': 114,
          'character': 'Gisele Yashar (uncredited)',
          'credit_id': '6400bc647a4ee700aaad91a5',
          'order': 35
        }
      ],
      'crew': [
        {
          'adult': false,
          'gender': 1,
          'id': 1302,
          'known_for_department': 'Production',
          'name': 'Susie Figgis',
          'original_name': 'Susie Figgis',
          'popularity': 4.648,
          'profile_path': '/yW6eiXF0CEXCHpqxqvEUZmq2mUq.jpg',
          'credit_id': '63fbc8cc344a8e007cba54a7',
          'department': 'Production',
          'job': 'Casting'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2519,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Sanja Milković Hays',
          'original_name': 'Sanja Milković Hays',
          'popularity': 2.354,
          'profile_path': null,
          'credit_id': '626872999f37b00066e55b94',
          'department': 'Costume & Make-Up',
          'job': 'Costume Design'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 7239,
          'known_for_department': 'Sound',
          'name': 'Peter Brown',
          'original_name': 'Peter Brown',
          'popularity': 1.55,
          'profile_path': null,
          'credit_id': '64840842e375c000ff48294b',
          'department': 'Sound',
          'job': 'Sound Designer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 7239,
          'known_for_department': 'Sound',
          'name': 'Peter Brown',
          'original_name': 'Peter Brown',
          'popularity': 1.55,
          'profile_path': null,
          'credit_id': '64840856d2b209014e08b50f',
          'department': 'Sound',
          'job': 'Supervising Sound Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 10570,
          'known_for_department': 'Production',
          'name': 'Joseph M. Caracciolo Jr.',
          'original_name': 'Joseph M. Caracciolo Jr.',
          'popularity': 2.862,
          'profile_path': null,
          'credit_id': '63e6a620a3d027009f3b7072',
          'department': 'Production',
          'job': 'Executive Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 10570,
          'known_for_department': 'Production',
          'name': 'Joseph M. Caracciolo Jr.',
          'original_name': 'Joseph M. Caracciolo Jr.',
          'popularity': 2.862,
          'profile_path': null,
          'credit_id': '64836539c9dbf9013a0601aa',
          'department': 'Production',
          'job': 'Unit Production Manager'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 6041,
          'known_for_department': 'Sound',
          'name': 'Brian Tyler',
          'original_name': 'Brian Tyler',
          'popularity': 6.717,
          'profile_path': '/wLPLAOcEgA9vfNuXSX1QI1ajguU.jpg',
          'credit_id': '63ed29a6813cb6007942d32a',
          'department': 'Sound',
          'job': 'Original Music Composer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 8162,
          'known_for_department': 'Writing',
          'name': 'Gary Scott Thompson',
          'original_name': 'Gary Scott Thompson',
          'popularity': 11.225,
          'profile_path': '/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg',
          'credit_id': '584340739251416764001ee7',
          'department': 'Writing',
          'job': 'Characters'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 11874,
          'known_for_department': 'Production',
          'name': 'Neal H. Moritz',
          'original_name': 'Neal H. Moritz',
          'popularity': 3.66,
          'profile_path': '/pPvK5xZTp1PymWL5OGc7dtqvx9Q.jpg',
          'credit_id': '60d4e2233c887d0076f14538',
          'department': 'Production',
          'job': 'Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 13162,
          'known_for_department': 'Editing',
          'name': 'Dov Samuel',
          'original_name': 'Dov Samuel',
          'popularity': 1.137,
          'profile_path': null,
          'credit_id': '648337d3c9dbf900e3fef534',
          'department': 'Editing',
          'job': 'First Assistant Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 12835,
          'known_for_department': 'Acting',
          'name': 'Vin Diesel',
          'original_name': 'Vin Diesel',
          'popularity': 58.215,
          'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg',
          'credit_id': '613ee5ca149565006452a1d3',
          'department': 'Production',
          'job': 'Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 15227,
          'known_for_department': 'Crew',
          'name': 'Sharon Smith Holley',
          'original_name': 'Sharon Smith Holley',
          'popularity': 1.249,
          'profile_path': null,
          'credit_id': '64833828bf31f25055a024a9',
          'department': 'Visual Effects',
          'job': 'VFX Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 15355,
          'known_for_department': 'Crew',
          'name': 'Daniel Acon',
          'original_name': 'Daniel Acon',
          'popularity': 1.702,
          'profile_path': null,
          'credit_id': '646bc5007b7b4d00e4adfe1a',
          'department': 'Visual Effects',
          'job': 'Special Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 15911,
          'known_for_department': 'Crew',
          'name': 'Franco Maria Salamon',
          'original_name': 'Franco Maria Salamon',
          'popularity': 1.716,
          'profile_path': null,
          'credit_id': '646bbaf233a3760175d3eadd',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 18189,
          'known_for_department': 'Writing',
          'name': 'Mark Bomback',
          'original_name': 'Mark Bomback',
          'popularity': 5.999,
          'profile_path': '/sasLL2smKWuZUjYq7d9O2QQrN0G.jpg',
          'credit_id': '63e6a653d29bdd008c9dc80f',
          'department': 'Production',
          'job': 'Executive Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 17649,
          'known_for_department': 'Camera',
          'name': 'Alexander Witt',
          'original_name': 'Alexander Witt',
          'popularity': 4.127,
          'profile_path': '/hO1QZ7P3SRNom3Ap4YZPsgESUcx.jpg',
          'credit_id': '6483658ee375c000c5270353',
          'department': 'Camera',
          'job': 'Second Unit Director of Photography'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 17649,
          'known_for_department': 'Camera',
          'name': 'Alexander Witt',
          'original_name': 'Alexander Witt',
          'popularity': 4.127,
          'profile_path': '/hO1QZ7P3SRNom3Ap4YZPsgESUcx.jpg',
          'credit_id': '646c11d9a5046e0189429c3c',
          'department': 'Directing',
          'job': 'Second Unit Director'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 18865,
          'known_for_department': 'Directing',
          'name': 'Louis Leterrier',
          'original_name': 'Louis Leterrier',
          'popularity': 16.923,
          'profile_path': '/guzsaiGBEy1qi3Ffh2uPcqaURYN.jpg',
          'credit_id': '62700baac56d2d6f7690125e',
          'department': 'Directing',
          'job': 'Director'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 20292,
          'known_for_department': 'Art',
          'name': 'Jan Roelfs',
          'original_name': 'Jan Roelfs',
          'popularity': 2.24,
          'profile_path': null,
          'credit_id': '62a307cb35d1bc5106b7103b',
          'department': 'Art',
          'job': 'Production Design'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 24969,
          'known_for_department': 'Acting',
          'name': 'Henry Kingi',
          'original_name': 'Henry Kingi',
          'popularity': 3.296,
          'profile_path': '/cThdKH6fn4faqei4DC2H3BQNkgI.jpg',
          'credit_id': '647530241bf2660442a72065',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 29400,
          'known_for_department': 'Production',
          'name': 'Jeff Kirschenbaum',
          'original_name': 'Jeff Kirschenbaum',
          'popularity': 4.514,
          'profile_path': '/mt7lkSY2tvSpUQZoXa1ZW9UfvSc.jpg',
          'credit_id': '62cb7b2746aed4087e8706dc',
          'department': 'Production',
          'job': 'Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 29474,
          'known_for_department': 'Art',
          'name': 'Simon McGuire',
          'original_name': 'Simon McGuire',
          'popularity': 1.62,
          'profile_path': null,
          'credit_id': '6461b54de3fa2f00e403c89c',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 58191,
          'known_for_department': 'Writing',
          'name': 'Chris Morgan',
          'original_name': 'Chris Morgan',
          'popularity': 11.103,
          'profile_path': '/ksZGCknL4lQceoDpHzX0LH5AFQP.jpg',
          'credit_id': '63e6a639c2ff3d007c3c24a5',
          'department': 'Production',
          'job': 'Executive Producer'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 57029,
          'known_for_department': 'Production',
          'name': 'Amanda Lewis',
          'original_name': 'Amanda Lewis',
          'popularity': 1.62,
          'profile_path': null,
          'credit_id': '63e6a647d29bdd00845fc101',
          'department': 'Production',
          'job': 'Executive Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 58189,
          'known_for_department': 'Directing',
          'name': 'Justin Lin',
          'original_name': 'Justin Lin',
          'popularity': 10.116,
          'profile_path': '/w0ryazdt8iS3GBrjXfv0FIwvUGY.jpg',
          'credit_id': '63fbc89484f249007beffed5',
          'department': 'Writing',
          'job': 'Screenplay'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 58189,
          'known_for_department': 'Directing',
          'name': 'Justin Lin',
          'original_name': 'Justin Lin',
          'popularity': 10.116,
          'profile_path': '/w0ryazdt8iS3GBrjXfv0FIwvUGY.jpg',
          'credit_id': '6268725fc613ce00aa0fed40',
          'department': 'Production',
          'job': 'Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 58189,
          'known_for_department': 'Directing',
          'name': 'Justin Lin',
          'original_name': 'Justin Lin',
          'popularity': 10.116,
          'profile_path': '/w0ryazdt8iS3GBrjXfv0FIwvUGY.jpg',
          'credit_id': '646abd9333a376013b3ea59e',
          'department': 'Writing',
          'job': 'Story'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 58192,
          'known_for_department': 'Camera',
          'name': 'Stephen F. Windon',
          'original_name': 'Stephen F. Windon',
          'popularity': 0.758,
          'profile_path': null,
          'credit_id': '5f8f7b9efed59700394c199b',
          'department': 'Camera',
          'job': 'Director of Photography'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 58193,
          'known_for_department': 'Editing',
          'name': 'Kelly Matsumoto',
          'original_name': 'Kelly Matsumoto',
          'popularity': 4.597,
          'profile_path': null,
          'credit_id': '64631e4fa67254014367fd0e',
          'department': 'Editing',
          'job': 'Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 67695,
          'known_for_department': 'Sound',
          'name': 'Paul Rabjohns',
          'original_name': 'Paul Rabjohns',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '6483f782e375c0011c7f8bf5',
          'department': 'Sound',
          'job': 'Supervising Music Editor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 90635,
          'known_for_department': 'Production',
          'name': 'Samantha Vincent',
          'original_name': 'Samantha Vincent',
          'popularity': 6.866,
          'profile_path': null,
          'credit_id': '62cb7b39595a5612b8a43540',
          'department': 'Production',
          'job': 'Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 75636,
          'known_for_department': 'Crew',
          'name': 'Jalil Jay Lynch',
          'original_name': 'Jalil Jay Lynch',
          'popularity': 3.067,
          'profile_path': '/lpU7fTd5MTv4nXcmmr1WdPcKnVN.jpg',
          'credit_id': '648367f4e375c000ff47da48',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 30737,
          'known_for_department': 'Acting',
          'name': 'Bolek Polívka',
          'original_name': 'Bolek Polívka',
          'popularity': 2.034,
          'profile_path': '/gQ40joDui2BoDrMplvGERa1WVQC.jpg',
          'credit_id': '646bbaa07b7b4d0172d5709c',
          'department': 'Crew',
          'job': 'Utility Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 83090,
          'known_for_department': 'Sound',
          'name': 'Todd Toon',
          'original_name': 'Todd Toon',
          'popularity': 1.406,
          'profile_path': null,
          'credit_id': '6483f725d2b209010c18c791',
          'department': 'Sound',
          'job': 'Sound Effects Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 112682,
          'known_for_department': 'Crew',
          'name': 'Spiro Razatos',
          'original_name': 'Spiro Razatos',
          'popularity': 4.151,
          'profile_path': '/tkJnvTnKa0t5HLi7dTKcXDrooFU.jpg',
          'credit_id': '6483042a99259c00e2f41874',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 112682,
          'known_for_department': 'Crew',
          'name': 'Spiro Razatos',
          'original_name': 'Spiro Razatos',
          'popularity': 4.151,
          'profile_path': '/tkJnvTnKa0t5HLi7dTKcXDrooFU.jpg',
          'credit_id': '6468550833a376013b3dc202',
          'department': 'Directing',
          'job': 'Second Unit Director'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 119183,
          'known_for_department': 'Crew',
          'name': 'Giorgio Antonini',
          'original_name': 'Giorgio Antonini',
          'popularity': 1.568,
          'profile_path': null,
          'credit_id': '646bb8f554a0980155e2eaa5',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 122274,
          'known_for_department': 'Visual Effects',
          'name': 'Peter Chiang',
          'original_name': 'Peter Chiang',
          'popularity': 2.498,
          'profile_path': null,
          'credit_id': '63fbc9126aa8e000f0b70ab7',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 122464,
          'known_for_department': 'Editing',
          'name': 'David Kern',
          'original_name': 'David Kern',
          'popularity': 1.134,
          'profile_path': null,
          'credit_id': '648300ede272600128791774',
          'department': 'Editing',
          'job': 'Additional Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 154668,
          'known_for_department': 'Acting',
          'name': 'Lee Spencer',
          'original_name': 'Lee Spencer',
          'popularity': 2.343,
          'profile_path': '/ohh0u2bN7YHtXQGMTN5JBrMCrpI.jpg',
          'credit_id': '64836665e2726000afc1f5f2',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 221636,
          'known_for_department': 'Acting',
          'name': 'Patrick Vo',
          'original_name': 'Patrick Vo',
          'popularity': 1.938,
          'profile_path': '/ui160lW3FLPt9GVeaerNjOqcvMf.jpg',
          'credit_id': '6466735d2bcf6700fe5f1e47',
          'department': 'Crew',
          'job': 'Fight Choreographer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 223238,
          'known_for_department': 'Visual Effects',
          'name': 'Hal Couzens',
          'original_name': 'Hal Couzens',
          'popularity': 1.686,
          'profile_path': null,
          'credit_id': '646bc61c7b7b4d0155f99149',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 228881,
          'known_for_department': 'Crew',
          'name': 'Olivier Schneider',
          'original_name': 'Olivier Schneider',
          'popularity': 5.321,
          'profile_path': '/i4pmJRPM1Qghf3t2oM9ZbhnKWn5.jpg',
          'credit_id': '648365d7d2b20900ad3bb5cf',
          'department': 'Crew',
          'job': 'Other'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 228881,
          'known_for_department': 'Crew',
          'name': 'Olivier Schneider',
          'original_name': 'Olivier Schneider',
          'popularity': 5.321,
          'profile_path': '/i4pmJRPM1Qghf3t2oM9ZbhnKWn5.jpg',
          'credit_id': '646bbca57b7b4d0138b0352e',
          'department': 'Directing',
          'job': 'Second Unit Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 563403,
          'known_for_department': 'Crew',
          'name': 'Jack Anderson',
          'original_name': 'Jack Anderson',
          'popularity': 1.564,
          'profile_path': null,
          'credit_id': '646bc510a5046e00e5b76f5e',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 937234,
          'known_for_department': 'Writing',
          'name': 'Dan Mazeau',
          'original_name': 'Dan Mazeau',
          'popularity': 3.506,
          'profile_path': null,
          'credit_id': '63fbc89c0c125500da1e524a',
          'department': 'Writing',
          'job': 'Screenplay'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 937234,
          'known_for_department': 'Writing',
          'name': 'Dan Mazeau',
          'original_name': 'Dan Mazeau',
          'popularity': 3.506,
          'profile_path': null,
          'credit_id': '646abd8c2bcf670172b1fe60',
          'department': 'Writing',
          'job': 'Story'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 968316,
          'known_for_department': 'Crew',
          'name': 'Andy Gill',
          'original_name': 'Andy Gill',
          'popularity': 2.385,
          'profile_path': '/uphgScM95clUsV8Rb2nwdiqCndX.jpg',
          'credit_id': '646674a633a376013b3cef95',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1014026,
          'known_for_department': 'Writing',
          'name': 'Zach Dean',
          'original_name': 'Zach Dean',
          'popularity': 2.473,
          'profile_path': '/hYmQIDnJZYiFigMXuUs3NSPKtAV.jpg',
          'credit_id': '646abd992bcf6700e3bb54b8',
          'department': 'Writing',
          'job': 'Story'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1157595,
          'known_for_department': 'Acting',
          'name': 'Nick McKinless',
          'original_name': 'Nick McKinless',
          'popularity': 1.316,
          'profile_path': null,
          'credit_id': '646bba2f54a09800e410428f',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1203510,
          'known_for_department': 'Crew',
          'name': 'Maurizio Salvatori',
          'original_name': 'Maurizio Salvatori',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bbc1354a09800e4104309',
          'department': 'Camera',
          'job': 'Grip'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1204245,
          'known_for_department': 'Editing',
          'name': 'Dylan Highsmith',
          'original_name': 'Dylan Highsmith',
          'popularity': 2.042,
          'profile_path': null,
          'credit_id': '64631e5ca6725400e3d2fd5c',
          'department': 'Editing',
          'job': 'Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1230574,
          'known_for_department': 'Crew',
          'name': 'Peter Miles',
          'original_name': 'Peter Miles',
          'popularity': 7.334,
          'profile_path': '/2Cu56fQK90ZWMq46B0WYMkF5m3I.jpg',
          'credit_id': '648365eebf31f2505f3dedc7',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1301638,
          'known_for_department': 'Acting',
          'name': 'Lee Charles',
          'original_name': 'Lee Charles',
          'popularity': 3.901,
          'profile_path': '/hPcEeF8mG9PiOJmnduVjq9yH9jD.jpg',
          'credit_id': '646bb94dc3514c2b0741b21c',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1321750,
          'known_for_department': 'Crew',
          'name': 'Kurt D. Lott',
          'original_name': 'Kurt D. Lott',
          'popularity': 0.84,
          'profile_path': '/lPUdu9RkkSy6xLxKRbVMV3Ruh2W.jpg',
          'credit_id': '646bb9f82bcf6700fe61a1c1',
          'department': 'Crew',
          'job': 'Utility Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1328758,
          'known_for_department': 'Sound',
          'name': 'Matthew Llewellyn',
          'original_name': 'Matthew Llewellyn',
          'popularity': 1.174,
          'profile_path': null,
          'credit_id': '64830116bf31f25055a00b72',
          'department': 'Sound',
          'job': 'Music Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1338230,
          'known_for_department': 'Visual Effects',
          'name': 'Meg Guidon',
          'original_name': 'Meg Guidon',
          'popularity': 1.094,
          'profile_path': null,
          'credit_id': '646bc6702bcf6700e3bbe3d5',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1338372,
          'known_for_department': 'Sound',
          'name': "Dan O'Connell",
          'original_name': "Dan O'Connell",
          'popularity': 2.202,
          'profile_path': null,
          'credit_id': '64830221e375c000ff47aee6',
          'department': 'Sound',
          'job': 'Foley Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1367493,
          'known_for_department': 'Sound',
          'name': 'John T. Cucci',
          'original_name': 'John T. Cucci',
          'popularity': 2.031,
          'profile_path': null,
          'credit_id': '6483024e99259c00e2f4178f',
          'department': 'Sound',
          'job': 'Foley Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1367499,
          'known_for_department': 'Acting',
          'name': 'Troy Robinson',
          'original_name': 'Troy Robinson',
          'popularity': 3.342,
          'profile_path': '/eYnD3gE7Mjo26fQLuT0MSsVTMfq.jpg',
          'credit_id': '646788a02bcf67011bf28fea',
          'department': 'Crew',
          'job': 'Stunt Coordinator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1385516,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Victoria Conte',
          'original_name': 'Victoria Conte',
          'popularity': 1.009,
          'profile_path': null,
          'credit_id': '646bbc4533a3760101fbf2a9',
          'department': 'Costume & Make-Up',
          'job': 'Wardrobe Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1390367,
          'known_for_department': 'Lighting',
          'name': 'Perry Evans',
          'original_name': 'Perry Evans',
          'popularity': 1.594,
          'profile_path': null,
          'credit_id': '64833c22e272600147b939a1',
          'department': 'Lighting',
          'job': 'Gaffer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1390524,
          'known_for_department': 'Sound',
          'name': 'Jay Wilkinson',
          'original_name': 'Jay Wilkinson',
          'popularity': 1.242,
          'profile_path': null,
          'credit_id': '6483017be375c000e24e8911',
          'department': 'Sound',
          'job': 'Sound Designer'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1392908,
          'known_for_department': 'Visual Effects',
          'name': 'Karen M. Murphy',
          'original_name': 'Karen M. Murphy',
          'popularity': 1.748,
          'profile_path': null,
          'credit_id': '646bc6cd33a3760175d3edcd',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1393883,
          'known_for_department': 'Camera',
          'name': 'Peter Mountain',
          'original_name': 'Peter Mountain',
          'popularity': 1.553,
          'profile_path': null,
          'credit_id': '6483033e99259c00ff0dbeb1',
          'department': 'Camera',
          'job': 'Still Photographer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1394130,
          'known_for_department': 'Sound',
          'name': 'Frank A. Montaño',
          'original_name': 'Frank A. Montaño',
          'popularity': 2.132,
          'profile_path': null,
          'credit_id': '646b5ebd2bcf67011bf45f4f',
          'department': 'Sound',
          'job': 'Sound Re-Recording Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1394131,
          'known_for_department': 'Sound',
          'name': 'Jon Taylor',
          'original_name': 'Jon Taylor',
          'popularity': 1.788,
          'profile_path': null,
          'credit_id': '648300bcd2b209010c184b45',
          'department': 'Sound',
          'job': 'Sound Re-Recording Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1399865,
          'known_for_department': 'Visual Effects',
          'name': 'Chad Wiebe',
          'original_name': 'Chad Wiebe',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '63fbc992e4b57600bd38ff57',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1408293,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Linda D. Flowers',
          'original_name': 'Linda D. Flowers',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '6461b5076e0d72015c0f2eb2',
          'department': 'Costume & Make-Up',
          'job': 'Hairstylist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1413453,
          'known_for_department': 'Sound',
          'name': 'Stephen P. Robinson',
          'original_name': 'Stephen P. Robinson',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '646bb8cdd18572016192d144',
          'department': 'Sound',
          'job': 'Sound Designer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1417685,
          'known_for_department': 'Crew',
          'name': 'Gregory J. Barnett',
          'original_name': 'Gregory J. Barnett',
          'popularity': 2.875,
          'profile_path': '/97Gns4ZXSHaVcpMwJSUjH3etjCx.jpg',
          'credit_id': '646bb910a5046e00e5b76c56',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1418001,
          'known_for_department': 'Editing',
          'name': 'Ben Howdeshell',
          'original_name': 'Ben Howdeshell',
          'popularity': 0.994,
          'profile_path': null,
          'credit_id': '64833848c9dbf900e3fef569',
          'department': 'Visual Effects',
          'job': 'VFX Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1426845,
          'known_for_department': 'Crew',
          'name': 'Aleksandar Pejic',
          'original_name': 'Aleksandar Pejic',
          'popularity': 1.166,
          'profile_path': null,
          'credit_id': '63fbc97684f249008db0beec',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1427849,
          'known_for_department': 'Directing',
          'name': 'Zoe Morgan',
          'original_name': 'Zoe Morgan',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '6482ffbebf31f250570575da',
          'department': 'Directing',
          'job': 'Script Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1435703,
          'known_for_department': 'Sound',
          'name': 'Glynna Grimala',
          'original_name': 'Glynna Grimala',
          'popularity': 2.188,
          'profile_path': null,
          'credit_id': '646bb8b1a5046e00e5b76c36',
          'department': 'Sound',
          'job': 'ADR Supervisor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1436199,
          'known_for_department': 'Crew',
          'name': 'Carol McConnaughey',
          'original_name': 'Carol McConnaughey',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '648364a1e375c00139bf88bb',
          'department': 'Crew',
          'job': 'Unit Publicist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1437798,
          'known_for_department': 'Costume & Make-Up',
          'name': "Roxy D'Alonzo",
          'original_name': "Roxy D'Alonzo",
          'popularity': 1.442,
          'profile_path': null,
          'credit_id': '63ddeb30ddd52d008482d8bd',
          'department': 'Costume & Make-Up',
          'job': 'Makeup Artist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1439735,
          'known_for_department': 'Visual Effects',
          'name': 'Corbin Mehl',
          'original_name': 'Corbin Mehl',
          'popularity': 1.546,
          'profile_path': null,
          'credit_id': '648304fa99259c00e2f418d3',
          'department': 'Editing',
          'job': 'Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1439747,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Andrew Hunt',
          'original_name': 'Andrew Hunt',
          'popularity': 1.62,
          'profile_path': null,
          'credit_id': '63ddeb6262f3350084a6a119',
          'department': 'Costume & Make-Up',
          'job': 'Costume Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1439749,
          'known_for_department': 'Editing',
          'name': 'Laura Steiger',
          'original_name': 'Laura Steiger',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '6483051fbf31f25057057856',
          'department': 'Editing',
          'job': 'Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1441365,
          'known_for_department': 'Camera',
          'name': 'Peter Wilke',
          'original_name': 'Peter Wilke',
          'popularity': 1.186,
          'profile_path': null,
          'credit_id': '64833528c9dbf900ad4523a6',
          'department': 'Camera',
          'job': '\"A\" Camera Operator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1450955,
          'known_for_department': 'Production',
          'name': 'Lex Donovan',
          'original_name': 'Lex Donovan',
          'popularity': 0.611,
          'profile_path': null,
          'credit_id': '64833660e375c000c526ed16',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1451649,
          'known_for_department': 'Sound',
          'name': 'Paul Drenning',
          'original_name': 'Paul Drenning',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '648301f6c9dbf900e3fedafc',
          'department': 'Sound',
          'job': 'ADR Mixer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1460571,
          'known_for_department': 'Camera',
          'name': 'Jeremiah Kent',
          'original_name': 'Jeremiah Kent',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '6483f501d2b209014e08a8ad',
          'department': 'Camera',
          'job': 'Second Assistant \"A\" Camera'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1470154,
          'known_for_department': 'Art',
          'name': 'Matthew Clark',
          'original_name': 'Matthew Clark',
          'popularity': 1.01,
          'profile_path': null,
          'credit_id': '6483344799259c011c3f8f57',
          'department': 'Art',
          'job': 'Graphic Designer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1531509,
          'known_for_department': 'Visual Effects',
          'name': 'Stanislas de Lesquen',
          'original_name': 'Stanislas de Lesquen',
          'popularity': 0.709,
          'profile_path': null,
          'credit_id': '646bc62ba5046e012468f570',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1536539,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Deborah Taylor',
          'original_name': 'Deborah Taylor',
          'popularity': 1.263,
          'profile_path': null,
          'credit_id': '648336fec9dbf900c571027d',
          'department': 'Costume & Make-Up',
          'job': 'Key Makeup Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1537508,
          'known_for_department': 'Camera',
          'name': 'Craig Grossmueller',
          'original_name': 'Craig Grossmueller',
          'popularity': 1.008,
          'profile_path': null,
          'credit_id': '6483f516c9dbf900ad458244',
          'department': 'Camera',
          'job': 'First Assistant \"B\" Camera'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1543196,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Jacqueline Fernandez',
          'original_name': 'Jacqueline Fernandez',
          'popularity': 1.769,
          'profile_path': null,
          'credit_id': '63ddeb25cd2046009d4e8eb5',
          'department': 'Costume & Make-Up',
          'job': 'Makeup Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1543254,
          'known_for_department': 'Crew',
          'name': 'Peter Krumov',
          'original_name': 'Peter Krumov',
          'popularity': 1.477,
          'profile_path': null,
          'credit_id': '646b5f1954a0980155e2c992',
          'department': 'Art',
          'job': 'Set Dresser'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1546028,
          'known_for_department': 'Art',
          'name': 'Andrew Palmer',
          'original_name': 'Andrew Palmer',
          'popularity': 1.629,
          'profile_path': null,
          'credit_id': '6461b556a6725400e3d2361f',
          'department': 'Art',
          'job': 'Supervising Art Director'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1548455,
          'known_for_department': 'Sound',
          'name': 'Shane Hayes',
          'original_name': 'Shane Hayes',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '6483f7ef99259c00accc5f2e',
          'department': 'Sound',
          'job': 'Other'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1548953,
          'known_for_department': 'Production',
          'name': 'Dan Clay',
          'original_name': 'Dan Clay',
          'popularity': 1.131,
          'profile_path': null,
          'credit_id': '6461b521ef8b320155554c40',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1550186,
          'known_for_department': 'Art',
          'name': 'Benton Jew',
          'original_name': 'Benton Jew',
          'popularity': 1.008,
          'profile_path': '/wiYoRBYQ5IxoiZIDs3o3uEHDl3p.jpg',
          'credit_id': '6483332ac9dbf9013a05ebd7',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1552475,
          'known_for_department': 'Camera',
          'name': 'Taylor Matheson',
          'original_name': 'Taylor Matheson',
          'popularity': 0.994,
          'profile_path': null,
          'credit_id': '6483f4f1e2726000e8c0657a',
          'department': 'Camera',
          'job': 'First Assistant \"A\" Camera'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1553295,
          'known_for_department': 'Production',
          'name': 'David Cain',
          'original_name': 'David Cain',
          'popularity': 2.663,
          'profile_path': null,
          'credit_id': '63e6a62fd29bdd00b2f99cf4',
          'department': 'Production',
          'job': 'Executive Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1553295,
          'known_for_department': 'Production',
          'name': 'David Cain',
          'original_name': 'David Cain',
          'popularity': 2.663,
          'profile_path': null,
          'credit_id': '64836546bf31f25054b52c9a',
          'department': 'Production',
          'job': 'Unit Production Manager'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1581175,
          'known_for_department': 'Art',
          'name': 'James Doh',
          'original_name': 'James Doh',
          'popularity': 1.574,
          'profile_path': null,
          'credit_id': '64833310bf31f25055a0226e',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1584868,
          'known_for_department': 'Art',
          'name': 'Chris Heap',
          'original_name': 'Chris Heap',
          'popularity': 1.771,
          'profile_path': null,
          'credit_id': '646b5f0554a0980155e2c982',
          'department': 'Art',
          'job': 'Standby Art Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1636660,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Jessica Pazdernik',
          'original_name': 'Jessica Pazdernik',
          'popularity': 1.094,
          'profile_path': null,
          'credit_id': '63ddeb4be55937008769ffde',
          'department': 'Costume & Make-Up',
          'job': 'Costume Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1669401,
          'known_for_department': 'Production',
          'name': 'Kirsty Kinnear',
          'original_name': 'Kirsty Kinnear',
          'popularity': 4.117,
          'profile_path': null,
          'credit_id': '63fbc8c8344a8e00aa1be492',
          'department': 'Production',
          'job': 'Casting'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1683365,
          'known_for_department': 'Art',
          'name': 'Josh Sheppard',
          'original_name': 'Josh Sheppard',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '648332e4bf31f2505f3dd9d9',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1685991,
          'known_for_department': 'Sound',
          'name': 'John Casali',
          'original_name': 'John Casali',
          'popularity': 1.799,
          'profile_path': null,
          'credit_id': '6461b58aa6725401436733d9',
          'department': 'Sound',
          'job': 'Production Sound Mixer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1685994,
          'known_for_department': 'Art',
          'name': 'Nick Pelham',
          'original_name': 'Nick Pelham',
          'popularity': 0.999,
          'profile_path': null,
          'credit_id': '648332b8e375c00139bf72fc',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1711214,
          'known_for_department': 'Directing',
          'name': 'Vincent Lascoumes',
          'original_name': 'Vincent Lascoumes',
          'popularity': 1.35,
          'profile_path': null,
          'credit_id': '646bbcd02bcf67011bf47ff4',
          'department': 'Directing',
          'job': 'First Assistant Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1725775,
          'known_for_department': 'Visual Effects',
          'name': 'Michael Grobe',
          'original_name': 'Michael Grobe',
          'popularity': 1.242,
          'profile_path': null,
          'credit_id': '63fbc95696e30b009fca3d3f',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1789618,
          'known_for_department': 'Art',
          'name': 'Adonay Marin Conde',
          'original_name': 'Adonay Marin Conde',
          'popularity': 1.214,
          'profile_path': null,
          'credit_id': '646bbd0d33a37600e67bad84',
          'department': 'Art',
          'job': 'Set Dresser'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1824262,
          'known_for_department': 'Camera',
          'name': 'Daniele Postiglione',
          'original_name': 'Daniele Postiglione',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bbc0454a09801386521cb',
          'department': 'Camera',
          'job': 'Grip'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1829852,
          'known_for_department': 'Camera',
          'name': 'Steve Ellingworth',
          'original_name': 'Steve Ellingworth',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '64833c89d2b209010c1867bd',
          'department': 'Camera',
          'job': 'Key Grip'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 1834185,
          'known_for_department': 'Crew',
          'name': 'Jade-Eleena Dregorius',
          'original_name': 'Jade-Eleena Dregorius',
          'popularity': 1.093,
          'profile_path': '/etgxJoL4HQ1PFRyC7i6dj7Rc22v.jpg',
          'credit_id': '648367d899259c01392aa713',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1844654,
          'known_for_department': 'Art',
          'name': 'Anthony Liberatore',
          'original_name': 'Anthony Liberatore',
          'popularity': 1.42,
          'profile_path': null,
          'credit_id': '64833282bf31f25054b51771',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1897684,
          'known_for_department': 'Acting',
          'name': 'Estelle Darnault',
          'original_name': 'Estelle Darnault',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '646bb97dc3514c2b0741b22e',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1946990,
          'known_for_department': 'Visual Effects',
          'name': 'Paul Jones',
          'original_name': 'Paul Jones',
          'popularity': 1.128,
          'profile_path': null,
          'credit_id': '63fbc94ee4b576009d1b382d',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 1962597,
          'known_for_department': 'Camera',
          'name': 'Carlo Postiglione',
          'original_name': 'Carlo Postiglione',
          'popularity': 1.214,
          'profile_path': null,
          'credit_id': '646bbbf7d1857201802df8e8',
          'department': 'Camera',
          'job': 'Grip'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 1981994,
          'known_for_department': 'Visual Effects',
          'name': 'Mariluz Noto',
          'original_name': 'Mariluz Noto',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646bc6db2bcf6700e3bbe3ed',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2020341,
          'known_for_department': 'Visual Effects',
          'name': 'François Lambert',
          'original_name': 'François Lambert',
          'popularity': 1.164,
          'profile_path': null,
          'credit_id': '63fbc97f57176f008544ad1f',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2046906,
          'known_for_department': 'Camera',
          'name': 'Tulio Duenas',
          'original_name': 'Tulio Duenas',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '6483f536c9dbf9013a064e43',
          'department': 'Camera',
          'job': 'First Assistant \"C\" Camera'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2069440,
          'known_for_department': 'Crew',
          'name': 'Dave Kneath',
          'original_name': 'Dave Kneath',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '646bc55fa5046e0189427869',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2094554,
          'known_for_department': 'Camera',
          'name': 'Sean Kisch',
          'original_name': 'Sean Kisch',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '6483f542e375c0011c7f8abd',
          'department': 'Camera',
          'job': 'First Assistant \"C\" Camera'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2095074,
          'known_for_department': 'Art',
          'name': 'Kathryn Pyle',
          'original_name': 'Kathryn Pyle',
          'popularity': 0.621,
          'profile_path': null,
          'credit_id': '6461b56e6e0d72013dcc88e8',
          'department': 'Art',
          'job': 'Set Decoration'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2116196,
          'known_for_department': 'Editing',
          'name': 'L. Dillon Thomas',
          'original_name': 'L. Dillon Thomas',
          'popularity': 1.31,
          'profile_path': null,
          'credit_id': '648337a1bf31f25055a02472',
          'department': 'Editing',
          'job': 'First Assistant Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2116242,
          'known_for_department': 'Art',
          'name': 'Andy Young',
          'original_name': 'Andy Young',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '6461b561dbbb420170a951d8',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2117037,
          'known_for_department': 'Crew',
          'name': "Declan O'Donnell",
          'original_name': "Declan O'Donnell",
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bc57a7b7b4d00e4adfe3f',
          'department': 'Crew',
          'job': 'Special Effects'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2127274,
          'known_for_department': 'Sound',
          'name': 'Jack Cucci',
          'original_name': 'Jack Cucci',
          'popularity': 1.609,
          'profile_path': null,
          'credit_id': '64830277c9dbf900e3fedb39',
          'department': 'Sound',
          'job': 'Foley Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2136902,
          'known_for_department': 'Sound',
          'name': 'Bryan Mendoza',
          'original_name': 'Bryan Mendoza',
          'popularity': 0.648,
          'profile_path': null,
          'credit_id': '6483f57399259c011c3fe842',
          'department': 'Sound',
          'job': 'Boom Operator'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2146964,
          'known_for_department': 'Camera',
          'name': 'Tom Wade',
          'original_name': 'Tom Wade',
          'popularity': 1.002,
          'profile_path': null,
          'credit_id': '6483354cd2b20900ad3ba064',
          'department': 'Camera',
          'job': '\"B\" Camera Operator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2256436,
          'known_for_department': 'Acting',
          'name': 'Tom Connelly',
          'original_name': 'Tom Connelly',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bb9707b7b4d0155f98d4b',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2258650,
          'known_for_department': 'Crew',
          'name': 'Christopher McGovern',
          'original_name': 'Christopher McGovern',
          'popularity': 1.178,
          'profile_path': null,
          'credit_id': '6483f564e375c000c527519f',
          'department': 'Camera',
          'job': 'Camera Loader'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2272446,
          'known_for_department': 'Crew',
          'name': 'Kim Fardy',
          'original_name': 'Kim Fardy',
          'popularity': 3.121,
          'profile_path': '/qDyu4KnaWLcnAwmh7RqfNMA2Iqh.jpg',
          'credit_id': '646bb9b2c3514c2b08517a41',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2331651,
          'known_for_department': 'Art',
          'name': 'Mark Button',
          'original_name': 'Mark Button',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '648331bde375c0011c7f3150',
          'department': 'Art',
          'job': 'Concept Artist'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 2363529,
          'known_for_department': 'Crew',
          'name': 'Richard Frazer',
          'original_name': 'Richard Frazer',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '646bc64fd18572010199767b',
          'department': 'Visual Effects',
          'job': 'Visual Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2378823,
          'known_for_department': 'Acting',
          'name': 'Brenda Lorena Garcia',
          'original_name': 'Brenda Lorena Garcia',
          'popularity': 5.355,
          'profile_path': '/yxoH72yZxvykjONyOdHQjwhf3DN.jpg',
          'credit_id': '64836738bf31f2505f3dee25',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2396253,
          'known_for_department': 'Production',
          'name': 'Matt Craufurd',
          'original_name': 'Matt Craufurd',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '64833642c9dbf90100cac2ee',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2396256,
          'known_for_department': 'Production',
          'name': 'Matt Risebrow',
          'original_name': 'Matt Risebrow',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '64833615d2b209010c186481',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2423284,
          'known_for_department': 'Crew',
          'name': 'Billy Clements',
          'original_name': 'Billy Clements',
          'popularity': 1.176,
          'profile_path': null,
          'credit_id': '648366f8d2b20900ca1e7f70',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2441229,
          'known_for_department': 'Crew',
          'name': 'Oleg Podobin',
          'original_name': 'Oleg Podobin',
          'popularity': 0.656,
          'profile_path': null,
          'credit_id': '646bba9133a3760175d3eabd',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2441460,
          'known_for_department': 'Visual Effects',
          'name': 'Alistair Williams',
          'original_name': 'Alistair Williams',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '6483031099259c00e2f417f4',
          'department': 'Visual Effects',
          'job': 'Special Effects Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2477289,
          'known_for_department': 'Production',
          'name': 'Samantha Arnold',
          'original_name': 'Samantha Arnold',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '648363b5e375c0011c7f45e4',
          'department': 'Directing',
          'job': 'Second Assistant Director'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2487281,
          'known_for_department': 'Art',
          'name': 'Chloe Kletsa',
          'original_name': 'Chloe Kletsa',
          'popularity': 1.538,
          'profile_path': null,
          'credit_id': '6461b5436e0d7200e31d2956',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2580099,
          'known_for_department': 'Sound',
          'name': 'Alan MacFeely',
          'original_name': 'Alan MacFeely',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '646bb8bfd1857201802df85c',
          'department': 'Sound',
          'job': 'Sound Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2757911,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Tania Couper',
          'original_name': 'Tania Couper',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '64833722bf31f25055a02435',
          'department': 'Costume & Make-Up',
          'job': 'Hair Supervisor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2833420,
          'known_for_department': 'Acting',
          'name': 'John P. Husky',
          'original_name': 'John P. Husky',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '64833892bf31f25055a024cb',
          'department': 'Visual Effects',
          'job': 'VFX Editor'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 2881848,
          'known_for_department': 'Crew',
          'name': 'Aurélia Agel',
          'original_name': 'Aurélia Agel',
          'popularity': 5.3,
          'profile_path': '/zHFdxVRVfBI4rrMBUsSyzUbZGzN.jpg',
          'credit_id': '646bb8e0c3514c2b0a33729f',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 2897052,
          'known_for_department': 'Sound',
          'name': 'Mike Lerma',
          'original_name': 'Mike Lerma',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '648301a0d2b209012dfc25ed',
          'department': 'Sound',
          'job': 'Dialogue Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3090492,
          'known_for_department': 'Art',
          'name': 'Lance Ashton Slaton',
          'original_name': 'Lance Ashton Slaton',
          'popularity': 1.214,
          'profile_path': null,
          'credit_id': '6483336ac9dbf900e3fef317',
          'department': 'Art',
          'job': 'Storyboard Artist'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 3104797,
          'known_for_department': 'Art',
          'name': 'Trixie Gardner',
          'original_name': 'Trixie Gardner',
          'popularity': 0.884,
          'profile_path': null,
          'credit_id': '646b5ef7d185720140321b56',
          'department': 'Art',
          'job': 'Set Dresser'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3114050,
          'known_for_department': 'Directing',
          'name': 'Luís Sérgio',
          'original_name': 'Luís Sérgio',
          'popularity': 0.982,
          'profile_path': null,
          'credit_id': '64836435bf31f25054b52c4f',
          'department': 'Directing',
          'job': 'Third Assistant Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3140713,
          'known_for_department': 'Visual Effects',
          'name': 'Jack Dorst',
          'original_name': 'Jack Dorst',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '646bc63854a098011b2c1ebe',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 3167141,
          'known_for_department': 'Production',
          'name': 'Katie Byles',
          'original_name': 'Katie Byles',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '64833134c9dbf900c570ffd1',
          'department': 'Production',
          'job': 'Production Manager'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3167155,
          'known_for_department': 'Art',
          'name': 'Alex Caldow',
          'original_name': 'Alex Caldow',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '648331d999259c00ff0dd6f7',
          'department': 'Art',
          'job': 'Concept Artist'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 3171603,
          'known_for_department': 'Sound',
          'name': 'Tavish Grade',
          'original_name': 'Tavish Grade',
          'popularity': 1.788,
          'profile_path': null,
          'credit_id': '646bb8a5d1857200e5a543c6',
          'department': 'Sound',
          'job': 'Foley Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3231760,
          'known_for_department': 'Production',
          'name': 'Danny Khoudary',
          'original_name': 'Danny Khoudary',
          'popularity': 1.389,
          'profile_path': null,
          'credit_id': '6483367fd2b20900ad3ba10c',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3258510,
          'known_for_department': 'Crew',
          'name': 'Carlos Castillo',
          'original_name': 'Carlos Castillo',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '64836613bf31f25055a037cb',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3397648,
          'known_for_department': 'Editing',
          'name': 'Mike Azevedo',
          'original_name': 'Mike Azevedo',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '648337bebf31f250570590b9',
          'department': 'Editing',
          'job': 'First Assistant Editor'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3446430,
          'known_for_department': 'Crew',
          'name': 'James Apps',
          'original_name': 'James Apps',
          'popularity': 1.0,
          'profile_path': null,
          'credit_id': '6483680699259c011c3fa3c4',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3448760,
          'known_for_department': 'Camera',
          'name': 'Peter Hayley-Barker',
          'original_name': 'Peter Hayley-Barker',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '64833ce299259c00e2f4352f',
          'department': 'Camera',
          'job': 'Best Boy Grip'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3455960,
          'known_for_department': 'Visual Effects',
          'name': 'Dayaliyah Lopez',
          'original_name': 'Dayaliyah Lopez',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bc690c3514c2b0a3375f0',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3480232,
          'known_for_department': 'Directing',
          'name': 'Kyle Williams',
          'original_name': 'Kyle Williams',
          'popularity': 0.652,
          'profile_path': null,
          'credit_id': '64836415e2726000e8c01bea',
          'department': 'Directing',
          'job': 'Third Assistant Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3485650,
          'known_for_department': 'Crew',
          'name': 'Matthew Bouchard',
          'original_name': 'Matthew Bouchard',
          'popularity': 0.75,
          'profile_path': null,
          'credit_id': '646bc51ed1857200e5a546a7',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3491157,
          'known_for_department': 'Sound',
          'name': 'Mikel Parraga-Wills',
          'original_name': 'Mikel Parraga-Wills',
          'popularity': 0.649,
          'profile_path': null,
          'credit_id': '64830294e272600107216890',
          'department': 'Sound',
          'job': 'Foley Mixer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3526390,
          'known_for_department': 'Camera',
          'name': 'Lee Godfrey',
          'original_name': 'Lee Godfrey',
          'popularity': 1.048,
          'profile_path': null,
          'credit_id': '64833cc2bf31f25054b51c61',
          'department': 'Camera',
          'job': 'Grip'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 3532449,
          'known_for_department': 'Acting',
          'name': 'Julia Schunevitsch',
          'original_name': 'Julia Schunevitsch',
          'popularity': 0.98,
          'profile_path': '/iCGvMtqjwsyLBYRGjY11wbmml9.jpg',
          'credit_id': '646bbb03a5046e00e5b76cd4',
          'department': 'Crew',
          'job': 'Stunt Double'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3572158,
          'known_for_department': 'Art',
          'name': 'Giulia Romolini',
          'original_name': 'Giulia Romolini',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646b5f3d54a098011b2bfa36',
          'department': 'Art',
          'job': 'Set Decoration Buyer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3593550,
          'known_for_department': 'Production',
          'name': 'Eleri Coulten',
          'original_name': 'Eleri Coulten',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '648335f2bf31f250569accca',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3596370,
          'known_for_department': 'Editing',
          'name': 'Delaney Del Vecchio',
          'original_name': 'Delaney Del Vecchio',
          'popularity': 0.608,
          'profile_path': null,
          'credit_id': '648338c1c9dbf9011dfb4cdf',
          'department': 'Visual Effects',
          'job': 'VFX Editor'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 3650884,
          'known_for_department': 'Visual Effects',
          'name': 'James Schembri',
          'original_name': 'James Schembri',
          'popularity': 1.048,
          'profile_path': null,
          'credit_id': '646bc705d18572016192d53a',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3665887,
          'known_for_department': 'Crew',
          'name': 'Ricardo Coelho',
          'original_name': 'Ricardo Coelho',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '646bc52d7b7b4d011b7971d7',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3665900,
          'known_for_department': 'Crew',
          'name': 'Valter Évora',
          'original_name': 'Valter Évora',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646bc5c433a3760101fbf4d9',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3693862,
          'known_for_department': 'Production',
          'name': 'Danielle Stanners',
          'original_name': 'Danielle Stanners',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '6483359199259c011c3f8ffe',
          'department': 'Production',
          'job': 'Production Coordinator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3734578,
          'known_for_department': 'Crew',
          'name': 'Aaron Parrott',
          'original_name': 'Aaron Parrott',
          'popularity': 1.614,
          'profile_path': null,
          'credit_id': '646bc5882bcf670155842a66',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3804025,
          'known_for_department': 'Directing',
          'name': 'Brunella De Cola',
          'original_name': 'Brunella De Cola',
          'popularity': 1.22,
          'profile_path': null,
          'credit_id': '6461b52ddbbb420153068abc',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3812676,
          'known_for_department': 'Visual Effects',
          'name': 'Tommy Leigh',
          'original_name': 'Tommy Leigh',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646bc69dc3514c2b0a3375f5',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3845493,
          'known_for_department': 'Visual Effects',
          'name': 'David Clifton',
          'original_name': 'David Clifton',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646bc609a5046e012468f568',
          'department': 'Visual Effects',
          'job': 'VFX Artist'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3852774,
          'known_for_department': 'Crew',
          'name': 'Nathan Grant',
          'original_name': 'Nathan Grant',
          'popularity': 0.608,
          'profile_path': null,
          'credit_id': '6483376bc9dbf900e3fef50a',
          'department': 'Costume & Make-Up',
          'job': 'Costumer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3880571,
          'known_for_department': 'Art',
          'name': 'Olivia Dibs',
          'original_name': 'Olivia Dibs',
          'popularity': 1.284,
          'profile_path': null,
          'credit_id': '646b5eeb2bcf6700e3bbc228',
          'department': 'Art',
          'job': 'Set Decoration Buyer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 3897577,
          'known_for_department': 'Art',
          'name': 'Joshua Benedetti',
          'original_name': 'Joshua Benedetti',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '648335dabf31f2505f3ddb31',
          'department': 'Production',
          'job': 'Location Manager'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 4062789,
          'known_for_department': 'Art',
          'name': 'Miranda Keeble',
          'original_name': 'Miranda Keeble',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '6461b53a8c44b90119cb1352',
          'department': 'Art',
          'job': 'Art Direction'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 4074776,
          'known_for_department': 'Art',
          'name': 'Jourdan McKee',
          'original_name': 'Jourdan McKee',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '646b5f2b33a37600e67b90bd',
          'department': 'Art',
          'job': 'Assistant Art Director'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4074777,
          'known_for_department': 'Art',
          'name': 'Morena Trevisiol',
          'original_name': 'Morena Trevisiol',
          'popularity': 0.923,
          'profile_path': null,
          'credit_id': '646b5f4d54a098011b2bfa4b',
          'department': 'Art',
          'job': 'Set Decoration Buyer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075433,
          'known_for_department': 'Crew',
          'name': 'Brittany Marcotte',
          'original_name': 'Brittany Marcotte',
          'popularity': 1.094,
          'profile_path': null,
          'credit_id': '6483674d99259c00ff0def0a',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075434,
          'known_for_department': 'Crew',
          'name': 'Caitlin McNerney',
          'original_name': 'Caitlin McNerney',
          'popularity': 0.694,
          'profile_path': null,
          'credit_id': '6483676bc9dbf900c57116e9',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075444,
          'known_for_department': 'Crew',
          'name': 'Anastajah Stearns',
          'original_name': 'Anastajah Stearns',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '646bbb532bcf67013896044a',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075447,
          'known_for_department': 'Crew',
          'name': 'Arttu Stenberg',
          'original_name': 'Arttu Stenberg',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '648366adc9dbf9013a060226',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075451,
          'known_for_department': 'Crew',
          'name': 'Oli Ward',
          'original_name': 'Oli Ward',
          'popularity': 0.615,
          'profile_path': null,
          'credit_id': '646bbb7a2bcf6700fe61a225',
          'department': 'Crew',
          'job': 'Stunts'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075464,
          'known_for_department': 'Costume & Make-Up',
          'name': 'Chiara Ciotti',
          'original_name': 'Chiara Ciotti',
          'popularity': 1.22,
          'profile_path': null,
          'credit_id': '646bbc362bcf670172b28f9a',
          'department': 'Costume & Make-Up',
          'job': 'Set Costumer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075469,
          'known_for_department': 'Art',
          'name': 'Virgilio Leandro',
          'original_name': 'Virgilio Leandro',
          'popularity': 1.4,
          'profile_path': null,
          'credit_id': '646bbd36d1857201019973b4',
          'department': 'Art',
          'job': 'Set Dresser'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075492,
          'known_for_department': 'Crew',
          'name': 'Joshua Connaway',
          'original_name': 'Joshua Connaway',
          'popularity': 0.694,
          'profile_path': null,
          'credit_id': '646bc53ca5046e018942785f',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075493,
          'known_for_department': 'Crew',
          'name': 'Andrea Ghellere',
          'original_name': 'Andrea Ghellere',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '646bc5507b7b4d0155f99105',
          'department': 'Crew',
          'job': 'Special Effects Technician'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075494,
          'known_for_department': 'Crew',
          'name': 'Stuart Lovelock',
          'original_name': 'Stuart Lovelock',
          'popularity': 0.694,
          'profile_path': null,
          'credit_id': '646bc56c2bcf67013896072d',
          'department': 'Crew',
          'job': 'Special Effects'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075495,
          'known_for_department': 'Crew',
          'name': 'Leon Van Der Walt',
          'original_name': 'Leon Van Der Walt',
          'popularity': 0.84,
          'profile_path': null,
          'credit_id': '646bc59e7b7b4d011b7971ed',
          'department': 'Crew',
          'job': 'Special Effects'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4075506,
          'known_for_department': 'Visual Effects',
          'name': 'Renée MacCarthy',
          'original_name': 'Renée MacCarthy',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '646bc6acc3514c2b0bf36e0a',
          'department': 'Visual Effects',
          'job': 'Visual Effects Producer'
        },
        {
          'adult': false,
          'gender': 1,
          'id': 4104243,
          'known_for_department': 'Art',
          'name': 'Annabel Gibb',
          'original_name': 'Annabel Gibb',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '64833484bf31f250569acbfb',
          'department': 'Art',
          'job': 'Graphic Designer'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4104274,
          'known_for_department': 'Crew',
          'name': 'Fiona Cousins',
          'original_name': 'Fiona Cousins',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '64833af0e2726000c92fef81',
          'department': 'Crew',
          'job': 'Special Effects Coordinator'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4104520,
          'known_for_department': 'Directing',
          'name': 'Nick White',
          'original_name': 'Nick White',
          'popularity': 0.608,
          'profile_path': null,
          'credit_id': '648363fabf31f2505880d480',
          'department': 'Directing',
          'job': 'Third Assistant Director'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 4105289,
          'known_for_department': 'Camera',
          'name': 'Holden Miller',
          'original_name': 'Holden Miller',
          'popularity': 0.98,
          'profile_path': null,
          'credit_id': '6483f52ae375c000acc505eb',
          'department': 'Camera',
          'job': 'Second Assistant \"B\" Camera'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 4105290,
          'known_for_department': 'Camera',
          'name': 'Augustus Bechtold',
          'original_name': 'Augustus Bechtold',
          'popularity': 1.38,
          'profile_path': null,
          'credit_id': '6483f555e375c000c5275192',
          'department': 'Camera',
          'job': 'Second Assistant \"C\" Camera'
        },
        {
          'adult': false,
          'gender': 0,
          'id': 4105293,
          'known_for_department': 'Camera',
          'name': 'Madie Ramser',
          'original_name': 'Madie Ramser',
          'popularity': 0.608,
          'profile_path': null,
          'credit_id': '6483f59599259c00c5b44b00',
          'department': 'Camera',
          'job': 'Digital Imaging Technician'
        },
        {
          'adult': false,
          'gender': 2,
          'id': 4105310,
          'known_for_department': 'Crew',
          'name': 'Michael Serr',
          'original_name': 'Michael Serr',
          'popularity': 0.6,
          'profile_path': null,
          'credit_id': '6483f819e272600128798855',
          'department': 'Crew',
          'job': 'Security'
        }
      ]
    });
    return SizedBox(
      height: height * 0.25,
      width: width * 0.97,
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: credits.cast.length,
        itemBuilder: (context, index) {
          return SizedBox(
            width: width * 0.32,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                CircleAvatar(
                  radius: height * 0.06,
                  backgroundImage: FadeInImage.assetNetwork(
                    placeholder: placeholder,
                    image:
                        ProcessImage.processProfileImageLink(credits.cast[index].profilePath),
                  ).image,
                ),
                SizedBox(height: height * 0.01,width: width*0.3,),
                Text(
                  credits.cast[index].name.length > 15
                      ? '${credits.cast[index].name.substring(0, 15)}...'
                      : credits.cast[index].name,
                  style: Theme.of(context).textTheme.titleSmall,
                  maxLines: 2,
                ),
                SizedBox(
                  width: width * 0.22,
                  child: const Divider(
                    color: Colors.white,
                    thickness: 1,
                  ),
                ),
                Text(
                  credits.cast[index].character.length > 15
                      ? '${credits.cast[index].character.substring(0, 15)}...'
                      : credits.cast[index].character,
                  style: Theme.of(context).textTheme.titleSmall,
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
