import 'dart:convert';

import 'package:cinemate/models/movie_credits_response_model.dart';
import 'package:cinemate/models/movie_model.dart';
import 'package:cinemate/models/now_playing_movies_response_model.dart';
import 'package:cinemate/models/popular_movies_response_model.dart';
import 'package:cinemate/models/similar_movies_response_model.dart';
import 'package:cinemate/models/trending_movies_response_model.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    var movieCreditsResposneJson={
      "id": 680,
      "cast": [
        {
          "adult": false,
          "gender": 2,
          "id": 8891,
          "known_for_department": "Acting",
          "name": "John Travolta",
          "original_name": "John Travolta",
          "popularity": 59.861,
          "profile_path": "/9axs7CGk01nmGqBAppDR92JHucn.jpg",
          "cast_id": 2,
          "character": "Vincent Vega",
          "credit_id": "52fe4269c3a36847f801ca99",
          "order": 0
        },
        {
          "adult": false,
          "gender": 2,
          "id": 2231,
          "known_for_department": "Acting",
          "name": "Samuel L. Jackson",
          "original_name": "Samuel L. Jackson",
          "popularity": 81.344,
          "profile_path": "/nCJJ3NVksYNxIzEHcyC1XziwPVj.jpg",
          "cast_id": 3,
          "character": "Jules Winnfield",
          "credit_id": "52fe4269c3a36847f801ca9d",
          "order": 1
        },
        {
          "adult": false,
          "gender": 1,
          "id": 139,
          "known_for_department": "Acting",
          "name": "Uma Thurman",
          "original_name": "Uma Thurman",
          "popularity": 58.035,
          "profile_path": "/sBgAZWi3o4FsnaTvnTNtK6jpQcF.jpg",
          "cast_id": 8,
          "character": "Mia Wallace",
          "credit_id": "52fe4269c3a36847f801cab7",
          "order": 2
        },
        {
          "adult": false,
          "gender": 2,
          "id": 62,
          "known_for_department": "Acting",
          "name": "Bruce Willis",
          "original_name": "Bruce Willis",
          "popularity": 34.466,
          "profile_path": "/caX3KtMU42EP3VLRFFBwqIIrch5.jpg",
          "cast_id": 1,
          "character": "Butch Coolidge",
          "credit_id": "52fe4269c3a36847f801ca95",
          "order": 3
        },
        {
          "adult": false,
          "gender": 2,
          "id": 10182,
          "known_for_department": "Acting",
          "name": "Ving Rhames",
          "original_name": "Ving Rhames",
          "popularity": 22.087,
          "profile_path": "/4gpLVNKPZlVucc4fT2fSZ7DksTK.jpg",
          "cast_id": 10,
          "character": "Marsellus Wallace",
          "credit_id": "52fe4269c3a36847f801cabf",
          "order": 4
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1037,
          "known_for_department": "Acting",
          "name": "Harvey Keitel",
          "original_name": "Harvey Keitel",
          "popularity": 33.24,
          "profile_path": "/7P30hza1neYWW3r7rSQOC736K2Z.jpg",
          "cast_id": 7,
          "character": "Winston \"The Wolf\" Wolfe",
          "credit_id": "52fe4269c3a36847f801cab3",
          "order": 5
        },
        {
          "adult": false,
          "gender": 2,
          "id": 7036,
          "known_for_department": "Acting",
          "name": "Eric Stoltz",
          "original_name": "Eric Stoltz",
          "popularity": 35.911,
          "profile_path": "/sP5tI3NVHrhmle5qotVz9q2mWfR.jpg",
          "cast_id": 9,
          "character": "Lance",
          "credit_id": "52fe4269c3a36847f801cabb",
          "order": 6
        },
        {
          "adult": false,
          "gender": 2,
          "id": 3129,
          "known_for_department": "Acting",
          "name": "Tim Roth",
          "original_name": "Tim Roth",
          "popularity": 30.754,
          "profile_path": "/qSizF2i9gz6c6DbAC5RoIq8sVqX.jpg",
          "cast_id": 11,
          "character": "Ringo (\"Pumpkin\")",
          "credit_id": "52fe4269c3a36847f801cac3",
          "order": 7
        },
        {
          "adult": false,
          "gender": 1,
          "id": 99,
          "known_for_department": "Acting",
          "name": "Amanda Plummer",
          "original_name": "Amanda Plummer",
          "popularity": 23.748,
          "profile_path": "/joHGUtEmXzJkH6ogEliiUKT9MNa.jpg",
          "cast_id": 12,
          "character": "Yolanda (\"Honey Bunny\")",
          "credit_id": "52fe4269c3a36847f801cac7",
          "order": 8
        },
        {
          "adult": false,
          "gender": 1,
          "id": 2319,
          "known_for_department": "Acting",
          "name": "Maria de Medeiros",
          "original_name": "Maria de Medeiros",
          "popularity": 10.924,
          "profile_path": "/xDo5mRSKXUZRmcZjUn42ICiyyI8.jpg",
          "cast_id": 13,
          "character": "Fabienne",
          "credit_id": "52fe4269c3a36847f801cacb",
          "order": 9
        },
        {
          "adult": false,
          "gender": 2,
          "id": 138,
          "known_for_department": "Directing",
          "name": "Quentin Tarantino",
          "original_name": "Quentin Tarantino",
          "popularity": 24.409,
          "profile_path": "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
          "cast_id": 35,
          "character": "Jimmie Dimmick",
          "credit_id": "52fe426ac3a36847f801cb3b",
          "order": 10
        },
        {
          "adult": false,
          "gender": 2,
          "id": 4690,
          "known_for_department": "Acting",
          "name": "Christopher Walken",
          "original_name": "Christopher Walken",
          "popularity": 31.556,
          "profile_path": "/ApgDL7nudR9T2GpjCG4vESgymO2.jpg",
          "cast_id": 32,
          "character": "Captain Koons",
          "credit_id": "52fe426ac3a36847f801cb2f",
          "order": 11
        },
        {
          "adult": false,
          "gender": 1,
          "id": 2165,
          "known_for_department": "Acting",
          "name": "Rosanna Arquette",
          "original_name": "Rosanna Arquette",
          "popularity": 27.316,
          "profile_path": "/qfS5G5VHW2gz2sYGDhIYRBoy3vY.jpg",
          "cast_id": 27,
          "character": "Jody",
          "credit_id": "52fe426ac3a36847f801cb1b",
          "order": 12
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11803,
          "known_for_department": "Acting",
          "name": "Peter Greene",
          "original_name": "Peter Greene",
          "popularity": 16.711,
          "profile_path": "/d7TiuUSlihDEuutZrF8IYrzEX1S.jpg",
          "cast_id": 26,
          "character": "Zed",
          "credit_id": "52fe426ac3a36847f801cb17",
          "order": 13
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11804,
          "known_for_department": "Acting",
          "name": "Duane Whitaker",
          "original_name": "Duane Whitaker",
          "popularity": 6.427,
          "profile_path": "/83nCcAaMYim24qWRwJcC1ZvfgK5.jpg",
          "cast_id": 28,
          "character": "Maynard",
          "credit_id": "52fe426ac3a36847f801cb1f",
          "order": 14
        },
        {
          "adult": false,
          "gender": 1,
          "id": 71836,
          "known_for_department": "Acting",
          "name": "Angela Jones",
          "original_name": "Angela Jones",
          "popularity": 10.212,
          "profile_path": "/jO5ULvqa6CeilVGLdVK6kVvlVsv.jpg",
          "cast_id": 39,
          "character": "Esmarelda Villalobos",
          "credit_id": "52fe426ac3a36847f801cb4b",
          "order": 15
        },
        {
          "adult": false,
          "gender": 2,
          "id": 31549,
          "known_for_department": "Acting",
          "name": "Phil LaMarr",
          "original_name": "Phil LaMarr",
          "popularity": 11.055,
          "profile_path": "/l5w0qABfsFBxjfWNnpFiaXnh4Nm.jpg",
          "cast_id": 40,
          "character": "Marvin",
          "credit_id": "52fe426ac3a36847f801cb4f",
          "order": 16
        },
        {
          "adult": false,
          "gender": 2,
          "id": 884,
          "known_for_department": "Acting",
          "name": "Steve Buscemi",
          "original_name": "Steve Buscemi",
          "popularity": 23.105,
          "profile_path": "/lQKdHMxfYcCBOvwRKBAxPZVNtkg.jpg",
          "cast_id": 31,
          "character": "Buddy Holly",
          "credit_id": "52fe426ac3a36847f801cb2b",
          "order": 17
        },
        {
          "adult": false,
          "gender": 1,
          "id": 33399,
          "known_for_department": "Acting",
          "name": "Bronagh Gallagher",
          "original_name": "Bronagh Gallagher",
          "popularity": 12.659,
          "profile_path": "/nFeWufPvkdYOj4wyjF0zb9tL1rb.jpg",
          "cast_id": 37,
          "character": "Trudi",
          "credit_id": "52fe426ac3a36847f801cb43",
          "order": 18
        },
        {
          "adult": false,
          "gender": 1,
          "id": 11807,
          "known_for_department": "Acting",
          "name": "Laura Lovelace",
          "original_name": "Laura Lovelace",
          "popularity": 3.101,
          "profile_path": "/1MLB30laQt2k80i15kdn0X7Zn5U.jpg",
          "cast_id": 34,
          "character": "Waitress",
          "credit_id": "52fe426ac3a36847f801cb37",
          "order": 19
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11805,
          "known_for_department": "Acting",
          "name": "Frank Whaley",
          "original_name": "Frank Whaley",
          "popularity": 27.711,
          "profile_path": "/ugs5aGtFvqVBgT8rcKEi1LyFur4.jpg",
          "cast_id": 30,
          "character": "Brett",
          "credit_id": "52fe426ac3a36847f801cb27",
          "order": 20
        },
        {
          "adult": false,
          "gender": 2,
          "id": 58552,
          "known_for_department": "Directing",
          "name": "Burr Steers",
          "original_name": "Burr Steers",
          "popularity": 3.064,
          "profile_path": "/k9rAVWornL0SUIykpjd3K3IfSll.jpg",
          "cast_id": 42,
          "character": "Roger",
          "credit_id": "52fe426ac3a36847f801cb57",
          "order": 21
        },
        {
          "adult": false,
          "gender": 2,
          "id": 3137,
          "known_for_department": "Acting",
          "name": "Paul Calderon",
          "original_name": "Paul Calderon",
          "popularity": 4.555,
          "profile_path": "/xIORhcIDmFMlaS3ZS3em1QiTkt5.jpg",
          "cast_id": 29,
          "character": "Paul",
          "credit_id": "52fe426ac3a36847f801cb23",
          "order": 22
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1174004,
          "known_for_department": "Acting",
          "name": "Jerome Patrick Hoban",
          "original_name": "Jerome Patrick Hoban",
          "popularity": 1.4,
          "profile_path": null,
          "cast_id": 49,
          "character": "Ed Sullivan",
          "credit_id": "52fe426ac3a36847f801cb73",
          "order": 23
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1224317,
          "known_for_department": "Acting",
          "name": "Michael Gilden",
          "original_name": "Michael Gilden",
          "popularity": 3.724,
          "profile_path": "/rZk317gtqOAF6MgImnJ6l5j9RQL.jpg",
          "cast_id": 48,
          "character": "Page for Phillip Morris",
          "credit_id": "52fe426ac3a36847f801cb6f",
          "order": 24
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174007,
          "known_for_department": "Acting",
          "name": "Gary Shorelle",
          "original_name": "Gary Shorelle",
          "popularity": 1.38,
          "profile_path": null,
          "cast_id": 54,
          "character": "Ricky Nelson",
          "credit_id": "52fe426ac3a36847f801cb87",
          "order": 25
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1174000,
          "known_for_department": "Acting",
          "name": "Susan Griffiths",
          "original_name": "Susan Griffiths",
          "popularity": 5.141,
          "profile_path": "/9qfVueDuicLOLTjlTcUtInbcFBl.jpg",
          "cast_id": 43,
          "character": "Marilyn Monroe",
          "credit_id": "52fe426ac3a36847f801cb5b",
          "order": 26
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174001,
          "known_for_department": "Acting",
          "name": "Eric Clark",
          "original_name": "Eric Clark",
          "popularity": 1.571,
          "profile_path": null,
          "cast_id": 44,
          "character": "James Dean",
          "credit_id": "52fe426ac3a36847f801cb5f",
          "order": 27
        },
        {
          "adult": false,
          "gender": 2,
          "id": 54855,
          "known_for_department": "Acting",
          "name": "Joseph Pilato",
          "original_name": "Joseph Pilato",
          "popularity": 3.977,
          "profile_path": "/msCVPwTXO9jWOhY6IGb6FP8oH6b.jpg",
          "cast_id": 45,
          "character": "Dean Martin",
          "credit_id": "52fe426ac3a36847f801cb63",
          "order": 28
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1174008,
          "known_for_department": "Acting",
          "name": "Brad Blumenthal",
          "original_name": "Brad Blumenthal",
          "popularity": 2.285,
          "profile_path": "/3MjdkSDoNurWzrQaKFfvglDT3x8.jpg",
          "cast_id": 55,
          "character": "Jerry Lewis",
          "credit_id": "52fe426ac3a36847f801cb8b",
          "order": 29
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1099751,
          "known_for_department": "Acting",
          "name": "Lorelei Leslie",
          "original_name": "Lorelei Leslie",
          "popularity": 3.769,
          "profile_path": "/6XUwwQSwk3Oys8bXmNoVE25SdNh.jpg",
          "cast_id": 53,
          "character": "Mamie van Doren",
          "credit_id": "52fe426ac3a36847f801cb83",
          "order": 30
        },
        {
          "adult": false,
          "gender": 2,
          "id": 107023,
          "known_for_department": "Acting",
          "name": "Emil Sitka",
          "original_name": "Emil Sitka",
          "popularity": 2.648,
          "profile_path": "/hsSU6n8qZTOYNvj2t27ArQIfF1r.jpg",
          "cast_id": 64,
          "character": "Hold Hands You Lovebirds (archive footage)",
          "credit_id": "52fe426ac3a36847f801cbb3",
          "order": 31
        },
        {
          "adult": false,
          "gender": 1,
          "id": 11162,
          "known_for_department": "Acting",
          "name": "Brenda Hillhouse",
          "original_name": "Brenda Hillhouse",
          "popularity": 2.933,
          "profile_path": "/8een5rR4vQZaUGI9sbsrerxQfqY.jpg",
          "cast_id": 46,
          "character": "Mrs. Coolidge - Butch's Mother",
          "credit_id": "52fe426ac3a36847f801cb67",
          "order": 32
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174002,
          "known_for_department": "Acting",
          "name": "Chandler Lindauer",
          "original_name": "Chandler Lindauer",
          "popularity": 2.603,
          "profile_path": null,
          "cast_id": 47,
          "character": "Young Butch",
          "credit_id": "52fe426ac3a36847f801cb6b",
          "order": 33
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174006,
          "known_for_department": "Acting",
          "name": "Sy Sher",
          "original_name": "Sy Sher",
          "popularity": 1.4,
          "profile_path": null,
          "cast_id": 52,
          "character": "Klondike",
          "credit_id": "52fe426ac3a36847f801cb7f",
          "order": 34
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1173999,
          "known_for_department": "Acting",
          "name": "Robert Ruth",
          "original_name": "Robert Ruth",
          "popularity": 3.977,
          "profile_path": "/7evl0ZWubDDaIHnRA546Aj8WGvG.jpg",
          "cast_id": 41,
          "character": "Sportscaster #1 - Coffee Shop",
          "credit_id": "52fe426ac3a36847f801cb53",
          "order": 35
        },
        {
          "adult": false,
          "gender": 0,
          "id": 46346,
          "known_for_department": "Acting",
          "name": "Rich Turner",
          "original_name": "Rich Turner",
          "popularity": 1.4,
          "profile_path": null,
          "cast_id": 56,
          "character": "Sportscaster #2",
          "credit_id": "52fe426ac3a36847f801cb8f",
          "order": 36
        },
        {
          "adult": false,
          "gender": 2,
          "id": 90337,
          "known_for_department": "Acting",
          "name": "Don Blakely",
          "original_name": "Don Blakely",
          "popularity": 2.393,
          "profile_path": "/hXbbhRj9Bxa2MSqVRXZKPzKOrJF.jpg",
          "cast_id": 51,
          "character": "Wilson's Trainer",
          "credit_id": "52fe426ac3a36847f801cb7b",
          "order": 37
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174005,
          "known_for_department": "Acting",
          "name": "Carl Allen",
          "original_name": "Carl Allen",
          "popularity": 1.62,
          "profile_path": null,
          "cast_id": 50,
          "character": "Dead Floyd Wilson",
          "credit_id": "52fe426ac3a36847f801cb77",
          "order": 38
        },
        {
          "adult": false,
          "gender": 1,
          "id": 157865,
          "known_for_department": "Acting",
          "name": "Karen Maruyama",
          "original_name": "Karen Maruyama",
          "popularity": 5.265,
          "profile_path": "/6XCu6ZFSkF8ppMO40Jx6HgDKJgj.jpg",
          "cast_id": 61,
          "character": "Gawker #1",
          "credit_id": "52fe426ac3a36847f801cba3",
          "order": 39
        },
        {
          "adult": false,
          "gender": 1,
          "id": 3138,
          "known_for_department": "Acting",
          "name": "Kathy Griffin",
          "original_name": "Kathy Griffin",
          "popularity": 5.657,
          "profile_path": "/psg895Ye46vGenRdX0EXvGOm92p.jpg",
          "cast_id": 60,
          "character": "Hit-and-run Witness",
          "credit_id": "52fe426ac3a36847f801cb9f",
          "order": 40
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1174009,
          "known_for_department": "Acting",
          "name": "Venessia Valentino",
          "original_name": "Venessia Valentino",
          "popularity": 3.192,
          "profile_path": null,
          "cast_id": 57,
          "character": "Pedestrian / Bonnie Dimmick",
          "credit_id": "52fe426ac3a36847f801cb93",
          "order": 41
        },
        {
          "adult": false,
          "gender": 1,
          "id": 65907,
          "known_for_department": "Acting",
          "name": "Linda Kaye",
          "original_name": "Linda Kaye",
          "popularity": 2.81,
          "profile_path": "/ftcHVQAFvaZPpAwZFI1uMmXUrlL.jpg",
          "cast_id": 59,
          "character": "Shot Woman",
          "credit_id": "52fe426ac3a36847f801cb9b",
          "order": 42
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1173998,
          "known_for_department": "Acting",
          "name": "Stephen Hibbert",
          "original_name": "Stephen Hibbert",
          "popularity": 2.503,
          "profile_path": null,
          "cast_id": 38,
          "character": "The Gimp",
          "credit_id": "52fe426ac3a36847f801cb47",
          "order": 43
        },
        {
          "adult": false,
          "gender": 1,
          "id": 19578,
          "known_for_department": "Acting",
          "name": "Alexis Arquette",
          "original_name": "Alexis Arquette",
          "popularity": 6.133,
          "profile_path": "/jNRBwGKXOZFWLI2ceff1sMUdxcE.jpg",
          "cast_id": 36,
          "character": "Man No. 4",
          "credit_id": "52fe426ac3a36847f801cb3f",
          "order": 44
        },
        {
          "adult": false,
          "gender": 1,
          "id": 11806,
          "known_for_department": "Acting",
          "name": "Julia Sweeney",
          "original_name": "Julia Sweeney",
          "popularity": 5.261,
          "profile_path": "/y0k7JXPsoLYG67sSlKdrT6c6a0M.jpg",
          "cast_id": 33,
          "character": "Raquel",
          "credit_id": "52fe426ac3a36847f801cb33",
          "order": 45
        },
        {
          "adult": false,
          "gender": 2,
          "id": 2545,
          "known_for_department": "Production",
          "name": "Lawrence Bender",
          "original_name": "Lawrence Bender",
          "popularity": 3.195,
          "profile_path": "/mZRwkIvUj8USnS7Jfwd6VdHkY2x.jpg",
          "cast_id": 58,
          "character": "Long Hair Yuppy Scum",
          "credit_id": "52fe426ac3a36847f801cb97",
          "order": 46
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1274295,
          "known_for_department": "Acting",
          "name": "Cie Allman",
          "original_name": "Cie Allman",
          "popularity": 3.941,
          "profile_path": "/2zyIj8rLX6iVIpvJrFfCVg9khtQ.jpg",
          "cast_id": 65,
          "character": "Winston Wolfe's Girlfriend at Party (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbb7",
          "order": 47
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1177915,
          "known_for_department": "Acting",
          "name": "Rene Beard",
          "original_name": "Rene Beard",
          "popularity": 2.268,
          "profile_path": "/41MgrwYElGdV7jbS8tsirgGpneo.jpg",
          "cast_id": 66,
          "character": "Bar Tender (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbbb",
          "order": 48
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1274296,
          "known_for_department": "Acting",
          "name": "Lori Pizzo",
          "original_name": "Lori Pizzo",
          "popularity": 2.304,
          "profile_path": "/9IXYGUiCjBumaWaI0STrugmSeYL.jpg",
          "cast_id": 67,
          "character": "Lucky Lady (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbbf",
          "order": 49
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1274297,
          "known_for_department": "Acting",
          "name": "Glendon Rich",
          "original_name": "Glendon Rich",
          "popularity": 1.38,
          "profile_path": null,
          "cast_id": 68,
          "character": "Drug Dealer (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbc3",
          "order": 50
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1274298,
          "known_for_department": "Acting",
          "name": "Devan Richardson",
          "original_name": "Devan Richardson",
          "popularity": 1.4,
          "profile_path": null,
          "cast_id": 69,
          "character": "Hopalong Cassidy (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbc7",
          "order": 51
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1274299,
          "known_for_department": "Acting",
          "name": "Ani Sava",
          "original_name": "Ani Sava",
          "popularity": 1.614,
          "profile_path": "/vZhhVCC0NXWaTqBRTFYV1urhoMp.jpg",
          "cast_id": 70,
          "character": "Woman in Bathroom (uncredited)",
          "credit_id": "52fe426ac3a36847f801cbcb",
          "order": 52
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1459067,
          "known_for_department": "Writing",
          "name": "Richard Rossi",
          "original_name": "Richard Rossi",
          "popularity": 1.4,
          "profile_path": "/cj4nsEqmJHRc9ki6382dGVOdUNe.jpg",
          "cast_id": 194,
          "character": "Diner Patron #2 (uncredited)",
          "credit_id": "5ef88932a284eb00368d3b27",
          "order": 53
        }
      ],
      "crew": [
        {
          "adult": false,
          "gender": 2,
          "id": 138,
          "known_for_department": "Directing",
          "name": "Quentin Tarantino",
          "original_name": "Quentin Tarantino",
          "popularity": 24.409,
          "profile_path": "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
          "credit_id": "52fe4269c3a36847f801caa9",
          "department": "Writing",
          "job": "Screenplay"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 138,
          "known_for_department": "Directing",
          "name": "Quentin Tarantino",
          "original_name": "Quentin Tarantino",
          "popularity": 24.409,
          "profile_path": "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
          "credit_id": "5e840df3da10f00018eb3962",
          "department": "Directing",
          "job": "Director"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 138,
          "known_for_department": "Directing",
          "name": "Quentin Tarantino",
          "original_name": "Quentin Tarantino",
          "popularity": 24.409,
          "profile_path": "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
          "credit_id": "5c456cde0e0a263ccdc614d9",
          "department": "Writing",
          "job": "Story"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 2545,
          "known_for_department": "Production",
          "name": "Lawrence Bender",
          "original_name": "Lawrence Bender",
          "popularity": 3.195,
          "profile_path": "/mZRwkIvUj8USnS7Jfwd6VdHkY2x.jpg",
          "credit_id": "52fe4269c3a36847f801cad1",
          "department": "Production",
          "job": "Producer"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 37333,
          "known_for_department": "Crew",
          "name": "Heidi Vogel",
          "original_name": "Heidi Vogel",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "56d4e476c3a3681e3c017853",
          "department": "Crew",
          "job": "Post Production Supervisor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 37334,
          "known_for_department": "Production",
          "name": "Paul Hellerman",
          "original_name": "Paul Hellerman",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cbaf",
          "department": "Production",
          "job": "Production Manager"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 3130,
          "known_for_department": "Acting",
          "name": "Jennifer Beals",
          "original_name": "Jennifer Beals",
          "popularity": 23.661,
          "profile_path": "/uJYKQC9GfRU3LHugCVDbAP1DrFH.jpg",
          "credit_id": "56d4e785c3a3681e3601569f",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 156,
          "known_for_department": "Editing",
          "name": "Sally Menke",
          "original_name": "Sally Menke",
          "popularity": 3.249,
          "profile_path": "/ggD5FOF6kgCz2X9NQESmxJwCCWc.jpg",
          "credit_id": "52fe426ac3a36847f801caef",
          "department": "Editing",
          "job": "Editor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 518,
          "known_for_department": "Acting",
          "name": "Danny DeVito",
          "original_name": "Danny DeVito",
          "popularity": 36.896,
          "profile_path": "/uLW4Y9yjtwxtVmcJfwHZ7sKJai4.jpg",
          "credit_id": "52fe4269c3a36847f801cad7",
          "department": "Production",
          "job": "Executive Producer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1307,
          "known_for_department": "Production",
          "name": "Bob Weinstein",
          "original_name": "Bob Weinstein",
          "popularity": 2.206,
          "profile_path": "/lCLIlmY3oZN9n0YgrH3i0oZygPU.jpg",
          "credit_id": "5597f2629251413d9f00134b",
          "department": "Production",
          "job": "Co-Executive Producer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 59839,
          "known_for_department": "Production",
          "name": "Harvey Weinstein",
          "original_name": "Harvey Weinstein",
          "popularity": 8.28,
          "profile_path": "/yUeo7hPc6fdHB2vy2zkGqg3bJyv.jpg",
          "credit_id": "5ad25c7b0e0a266c2b0169b3",
          "department": "Production",
          "job": "Co-Executive Producer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 5779,
          "known_for_department": "Art",
          "name": "David Wasco",
          "original_name": "David Wasco",
          "popularity": 1.708,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cb01",
          "department": "Art",
          "job": "Production Design"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 33685,
          "known_for_department": "Editing",
          "name": "Tatiana S. Riegel",
          "original_name": "Tatiana S. Riegel",
          "popularity": 2.707,
          "profile_path": "/mms5qpMvookGWLw2UZ54QqO9hES.jpg",
          "credit_id": "59cc13afc3a368770e0165c5",
          "department": "Editing",
          "job": "First Assistant Editor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 8297,
          "known_for_department": "Writing",
          "name": "Roger Avary",
          "original_name": "Roger Avary",
          "popularity": 6.042,
          "profile_path": "/eq810bljrpQ0FB0SUmUTGyxqFv6.jpg",
          "credit_id": "5c456cd4c3a368477a82a408",
          "department": "Writing",
          "job": "Story"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 4702,
          "known_for_department": "Production",
          "name": "Bill Unger",
          "original_name": "Bill Unger",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5ad25ecac3a3683ef90167ec",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 5507,
          "known_for_department": "Production",
          "name": "Ronnie Yeskel",
          "original_name": "Ronnie Yeskel",
          "popularity": 3.504,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cafb",
          "department": "Production",
          "job": "Casting"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 5381,
          "known_for_department": "Production",
          "name": "Michael Shamberg",
          "original_name": "Michael Shamberg",
          "popularity": 4.599,
          "profile_path": "/nFemswEbQG0j8Gy7NrnDNTzWe9K.jpg",
          "credit_id": "52fe4269c3a36847f801cadd",
          "department": "Production",
          "job": "Executive Producer"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 5382,
          "known_for_department": "Production",
          "name": "Stacey Sher",
          "original_name": "Stacey Sher",
          "popularity": 3.35,
          "profile_path": null,
          "credit_id": "52fe4269c3a36847f801cae3",
          "department": "Production",
          "job": "Executive Producer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 10630,
          "known_for_department": "Sound",
          "name": "Dean Beville",
          "original_name": "Dean Beville",
          "popularity": 1.96,
          "profile_path": null,
          "credit_id": "570fcb22c3a3684122000691",
          "department": "Sound",
          "job": "Sound Editor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 3115,
          "known_for_department": "Camera",
          "name": "Andrzej Sekula",
          "original_name": "Andrzej Sekula",
          "popularity": 6.236,
          "profile_path": "/8vPRxAkQC1j22qvadt0H8ZByqBb.jpg",
          "credit_id": "52fe426ac3a36847f801cae9",
          "department": "Camera",
          "job": "Director of Photography"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 6940,
          "known_for_department": "Sound",
          "name": "Karyn Rachtman",
          "original_name": "Karyn Rachtman",
          "popularity": 1.015,
          "profile_path": null,
          "credit_id": "563609bcc3a3681b5401b74f",
          "department": "Sound",
          "job": "Music Supervisor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 6828,
          "known_for_department": "Sound",
          "name": "Ken King",
          "original_name": "Ken King",
          "popularity": 2.268,
          "profile_path": null,
          "credit_id": "59cc1492c3a368773d01aae6",
          "department": "Sound",
          "job": "Production Sound Mixer"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 7902,
          "known_for_department": "Production",
          "name": "Ruth Lambert",
          "original_name": "Ruth Lambert",
          "popularity": 2.28,
          "profile_path": null,
          "credit_id": "56d4e667925141391f00209a",
          "department": "Production",
          "job": "Casting Associate"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11799,
          "known_for_department": "Production",
          "name": "Gary M. Zuckerbrod",
          "original_name": "Gary M. Zuckerbrod",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801caf5",
          "department": "Production",
          "job": "Casting"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11800,
          "known_for_department": "Art",
          "name": "Charles Collum",
          "original_name": "Charles Collum",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cb07",
          "department": "Art",
          "job": "Art Direction"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 11801,
          "known_for_department": "Art",
          "name": "Sandy Reynolds-Wasco",
          "original_name": "Sandy Reynolds-Wasco",
          "popularity": 2.588,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cb0d",
          "department": "Art",
          "job": "Set Decoration"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 11802,
          "known_for_department": "Costume & Make-Up",
          "name": "Betsy Heimann",
          "original_name": "Betsy Heimann",
          "popularity": 1.396,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cb13",
          "department": "Costume & Make-Up",
          "job": "Costume Design"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 11641,
          "known_for_department": "Acting",
          "name": "Scott Spiegel",
          "original_name": "Scott Spiegel",
          "popularity": 4.802,
          "profile_path": "/3dKveWiEUeQbAxC7o9AKkIUymPQ.jpg",
          "credit_id": "5ad25e739251417376015186",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 13165,
          "known_for_department": "Sound",
          "name": "Ezra Dweck",
          "original_name": "Ezra Dweck",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f27c9251415d3ef4dac1",
          "department": "Sound",
          "job": "Foley Mixer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 12997,
          "known_for_department": "Production",
          "name": "Richard N. Gladstein",
          "original_name": "Richard N. Gladstein",
          "popularity": 2.024,
          "profile_path": "/zXZVhSR8NWFjZd1nHA0WG0bflB.jpg",
          "credit_id": "5597f24fc3a36855db0013f9",
          "department": "Production",
          "job": "Co-Executive Producer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 53898,
          "known_for_department": "Editing",
          "name": "Andrew Dickler",
          "original_name": "Andrew Dickler",
          "popularity": 2.062,
          "profile_path": null,
          "credit_id": "573517dc925141672c0001aa",
          "department": "Crew",
          "job": "Editorial Staff"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 22054,
          "known_for_department": "Crew",
          "name": "Ken Lesco",
          "original_name": "Ken Lesco",
          "popularity": 1.646,
          "profile_path": "/2V2tdPMpe4XNXyd0xfkRKjUuNNQ.jpg",
          "credit_id": "56d4e590c3a3681e39015667",
          "department": "Crew",
          "job": "Stunt Coordinator"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 41655,
          "known_for_department": "Production",
          "name": "Jeff Olan",
          "original_name": "Jeff Olan",
          "popularity": 1.312,
          "profile_path": null,
          "credit_id": "56d4e696c3a3681e44017995",
          "department": "Production",
          "job": "Casting"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 46589,
          "known_for_department": "Costume & Make-Up",
          "name": "Mary Claire Hannan",
          "original_name": "Mary Claire Hannan",
          "popularity": 2.268,
          "profile_path": "/po5EDrudtAYk9azlv8Zkku7R3wU.jpg",
          "credit_id": "56d4e70f925141391f0020c1",
          "department": "Costume & Make-Up",
          "job": "Assistant Costume Designer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 58015,
          "known_for_department": "Production",
          "name": "Ricardo Mestres",
          "original_name": "Ricardo Mestres",
          "popularity": 0.618,
          "profile_path": null,
          "credit_id": "5ad25e429251417364015086",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 58809,
          "known_for_department": "Directing",
          "name": "Martin Kitrosser",
          "original_name": "Martin Kitrosser",
          "popularity": 3.027,
          "profile_path": null,
          "credit_id": "59cc138e9251412be101742d",
          "department": "Directing",
          "job": "Script Supervisor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 61076,
          "known_for_department": "Art",
          "name": "Daniel Bradford",
          "original_name": "Daniel Bradford",
          "popularity": 2.065,
          "profile_path": null,
          "credit_id": "59cc0fe5c3a368770e015faa",
          "department": "Art",
          "job": "Set Designer"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 61121,
          "known_for_department": "Production",
          "name": "Lou Arkoff",
          "original_name": "Lou Arkoff",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5ad25d67925141737601507c",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 79534,
          "known_for_department": "Production",
          "name": "Agnès B.",
          "original_name": "Agnès B.",
          "popularity": 1.708,
          "profile_path": "/i9nBTjzFddm4yZrNrvIXbPJw1u8.jpg",
          "credit_id": "5ad25d87925141736a014ff0",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 83351,
          "known_for_department": "Acting",
          "name": "Stephen Martines",
          "original_name": "Stephen Martines",
          "popularity": 1.469,
          "profile_path": "/abRIvgPHvgnZSPHH0cN20GJtIFR.jpg",
          "credit_id": "5ad25e310e0a266c28015f74",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 118868,
          "known_for_department": "Production",
          "name": "Emily Wolfe",
          "original_name": "Emily Wolfe",
          "popularity": 1.094,
          "profile_path": null,
          "credit_id": "59cc0f409251412bd9017d4e",
          "department": "Art",
          "job": "Art Department Coordinator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 121747,
          "known_for_department": "Acting",
          "name": "Emanuel Steward",
          "original_name": "Emanuel Steward",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5ad25ea00e0a266c2e015e2f",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 143893,
          "known_for_department": "Costume & Make-Up",
          "name": "Michelle Bühler",
          "original_name": "Michelle Bühler",
          "popularity": 1.532,
          "profile_path": null,
          "credit_id": "56d4e3a392514111eb0006ef",
          "department": "Costume & Make-Up",
          "job": "Makeup Artist"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 148455,
          "known_for_department": "Writing",
          "name": "Ziad Doueiri",
          "original_name": "Ziad Doueiri",
          "popularity": 2.218,
          "profile_path": "/oXfCFMbjWWqGD23hjXmGL1D5y2t.jpg",
          "credit_id": "56d4e80cc3a3681e500145fa",
          "department": "Camera",
          "job": "First Assistant Camera"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 209898,
          "known_for_department": "Camera",
          "name": "Mike Simpson",
          "original_name": "Mike Simpson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5ad25e57925141736c01512a",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 230436,
          "known_for_department": "Production",
          "name": "Barbara Harris",
          "original_name": "Barbara Harris",
          "popularity": 5.988,
          "profile_path": "/d1BGeZT2b81Wa9gCOPdrXGWUtmR.jpg",
          "credit_id": "5cc4cf2e9251412ba1fa42dc",
          "department": "Production",
          "job": "ADR Voice Casting"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 554887,
          "known_for_department": "Sound",
          "name": "Stephen Hunter Flick",
          "original_name": "Stephen Hunter Flick",
          "popularity": 1.891,
          "profile_path": null,
          "credit_id": "59cc14ae9251412b8f0194ec",
          "department": "Sound",
          "job": "Supervising Sound Editor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 960673,
          "known_for_department": "Art",
          "name": "Peter Borck",
          "original_name": "Peter Borck",
          "popularity": 1.619,
          "profile_path": null,
          "credit_id": "59cc0faf9251412bb3017b2e",
          "department": "Art",
          "job": "Leadman"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 999690,
          "known_for_department": "Crew",
          "name": "Terry Jackson",
          "original_name": "Terry Jackson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f2bdc3a36820b58431a2",
          "department": "Crew",
          "job": "Stunt Double"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1174010,
          "known_for_department": "Lighting",
          "name": "Vance Trussell",
          "original_name": "Vance Trussell",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "52fe426ac3a36847f801cba9",
          "department": "Lighting",
          "job": "Gaffer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1197438,
          "known_for_department": "Acting",
          "name": "Cameron",
          "original_name": "Cameron",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc133e9251412b98018a78",
          "department": "Crew",
          "job": "Stunts"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1197438,
          "known_for_department": "Acting",
          "name": "Cameron",
          "original_name": "Cameron",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc131e9251412bb301810a",
          "department": "Crew",
          "job": "Stand In"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1280435,
          "known_for_department": "Crew",
          "name": "Thomas L. Bellissimo",
          "original_name": "Thomas L. Bellissimo",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc124c9251412b8f019013",
          "department": "Crew",
          "job": "Makeup Effects"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1287672,
          "known_for_department": "Crew",
          "name": "Larry Fioritto",
          "original_name": "Larry Fioritto",
          "popularity": 1.62,
          "profile_path": null,
          "credit_id": "59cc1306c3a368773d01a75a",
          "department": "Crew",
          "job": "Special Effects Coordinator"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1328142,
          "known_for_department": "Production",
          "name": "Lee Stollman",
          "original_name": "Lee Stollman",
          "popularity": 1.96,
          "profile_path": "/whwcbXPUmybVWi9WiUfNTzhfetR.jpg",
          "credit_id": "5ad25eb50e0a266c1f017a51",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1341806,
          "known_for_department": "Art",
          "name": "Ray Maxwell",
          "original_name": "Ray Maxwell",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "59cc0f86c3a368776e018e99",
          "department": "Art",
          "job": "Construction Foreman"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1380055,
          "known_for_department": "Costume & Make-Up",
          "name": "Patia Prouty",
          "original_name": "Patia Prouty",
          "popularity": 1.614,
          "profile_path": null,
          "credit_id": "56d4e748c3a3681e390156d6",
          "department": "Costume & Make-Up",
          "job": "Set Costumer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1389625,
          "known_for_department": "Crew",
          "name": "Derek Raser",
          "original_name": "Derek Raser",
          "popularity": 4.438,
          "profile_path": null,
          "credit_id": "59cc13539251412b8b0199f4",
          "department": "Crew",
          "job": "Transportation Coordinator"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1395016,
          "known_for_department": "Art",
          "name": "Brian Markey",
          "original_name": "Brian Markey",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc0f719251412b8f018ac2",
          "department": "Art",
          "job": "Construction Coordinator"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1395281,
          "known_for_department": "Camera",
          "name": "Bob Gorelick",
          "original_name": "Bob Gorelick",
          "popularity": 1.615,
          "profile_path": null,
          "credit_id": "59cc117dc3a368770e01623d",
          "department": "Camera",
          "job": "Steadicam Operator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1397881,
          "known_for_department": "Costume & Make-Up",
          "name": "Audrey Futterman-Stern",
          "original_name": "Audrey Futterman-Stern",
          "popularity": 1.553,
          "profile_path": null,
          "credit_id": "56d4e4219251410bd1003a0a",
          "department": "Costume & Make-Up",
          "job": "Key Hair Stylist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1399999,
          "known_for_department": "Camera",
          "name": "Michael Levine",
          "original_name": "Michael Levine",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc11439251412be1017006",
          "department": "Camera",
          "job": "Camera Operator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1400837,
          "known_for_department": "Production",
          "name": "John A. Johnston",
          "original_name": "John A. Johnston",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f312c3a368493681ed72",
          "department": "Production",
          "job": "Assistant Location Manager"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1401260,
          "known_for_department": "Sound",
          "name": "Catherine Rowe",
          "original_name": "Catherine Rowe",
          "popularity": 1.614,
          "profile_path": null,
          "credit_id": "5cc5f2629251415d3ef4da7e",
          "department": "Sound",
          "job": "Foley Artist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1406792,
          "known_for_department": "Crew",
          "name": "Deborah Wuliger",
          "original_name": "Deborah Wuliger",
          "popularity": 1.094,
          "profile_path": null,
          "credit_id": "59cc1368c3a3687761018fd0",
          "department": "Crew",
          "job": "Unit Publicist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1410102,
          "known_for_department": "Art",
          "name": "Jonathan R. Hodges",
          "original_name": "Jonathan R. Hodges",
          "popularity": 1.614,
          "profile_path": null,
          "credit_id": "59cc1290c3a368773d01a682",
          "department": "Art",
          "job": "Property Master"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1411258,
          "known_for_department": "Costume & Make-Up",
          "name": "Linda Arnold",
          "original_name": "Linda Arnold",
          "popularity": 1.214,
          "profile_path": null,
          "credit_id": "57530c48c3a3685207003363",
          "department": "Costume & Make-Up",
          "job": "Hairstylist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1425675,
          "known_for_department": "Production",
          "name": "Cathryn Jaymes",
          "original_name": "Cathryn Jaymes",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5ad25dd70e0a266c28015f25",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1433718,
          "known_for_department": "Sound",
          "name": "Dana Gustafson",
          "original_name": "Dana Gustafson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc144bc3a368779701a1ef",
          "department": "Sound",
          "job": "Assistant Sound Editor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1440853,
          "known_for_department": "Editing",
          "name": "Donald Likovich",
          "original_name": "Donald Likovich",
          "popularity": 1.22,
          "profile_path": null,
          "credit_id": "56d4e8609251413402012038",
          "department": "Editing",
          "job": "Assistant Editor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1449705,
          "known_for_department": "Directing",
          "name": "Kevin McTurk",
          "original_name": "Kevin McTurk",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "60ffa24338e510005df22963",
          "department": "Crew",
          "job": "Special Effects Technician"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1530166,
          "known_for_department": "Sound",
          "name": "Kathy Nelson",
          "original_name": "Kathy Nelson",
          "popularity": 2.658,
          "profile_path": null,
          "credit_id": "563609d7925141616700c22f",
          "department": "Sound",
          "job": "Music Supervisor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1534236,
          "known_for_department": "Camera",
          "name": "Linda R. Chen",
          "original_name": "Linda R. Chen",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5ad25dac0e0a266c2e015d17",
          "department": "Crew",
          "job": "Thanks"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1537110,
          "known_for_department": "Sound",
          "name": "Billy Gottlieb",
          "original_name": "Billy Gottlieb",
          "popularity": 1.96,
          "profile_path": null,
          "credit_id": "5ad25c53c3a3683f0301781d",
          "department": "Sound",
          "job": "Assistant Music Supervisor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1542283,
          "known_for_department": "Acting",
          "name": "Adam Silver",
          "original_name": "Adam Silver",
          "popularity": 1.4,
          "profile_path": "/yme8cwRnMkrWGt4yr7X874JJSF6.jpg",
          "credit_id": "59cc0fc89251412be1016dfe",
          "department": "Art",
          "job": "Location Scout"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1545448,
          "known_for_department": "Sound",
          "name": "Mary Ramos",
          "original_name": "Mary Ramos",
          "popularity": 1.4,
          "profile_path": "/23BDqamvTnnbaFNRNPg34qS62En.jpg",
          "credit_id": "5cc5f34292514151ca05baf2",
          "department": "Sound",
          "job": "Music Coordinator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1545701,
          "known_for_department": "Art",
          "name": "Samantha Gore",
          "original_name": "Samantha Gore",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "59cc0f619251412b8f018aaa",
          "department": "Art",
          "job": "Assistant Art Director"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1547239,
          "known_for_department": "Costume & Make-Up",
          "name": "Jacqueline Aronson",
          "original_name": "Jacqueline Aronson",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "56d4e6d99251412c9600dbd1",
          "department": "Costume & Make-Up",
          "job": "Costume Supervisor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1552002,
          "known_for_department": "Costume & Make-Up",
          "name": "Bill Fletcher",
          "original_name": "Bill Fletcher",
          "popularity": 1.63,
          "profile_path": null,
          "credit_id": "56d4e3eec3a3681e39015604",
          "department": "Costume & Make-Up",
          "job": "Wigmaker"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1562457,
          "known_for_department": "Sound",
          "name": "Rolf Johnson",
          "original_name": "Rolf Johnson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc14769251412bd901867b",
          "department": "Sound",
          "job": "Music Editor"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1564233,
          "known_for_department": "Editing",
          "name": "Mike Stanwick",
          "original_name": "Mike Stanwick",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5701578fc3a368569c000340",
          "department": "Editing",
          "job": "Color Timer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1584695,
          "known_for_department": "Lighting",
          "name": "Bruce Jagoda",
          "original_name": "Bruce Jagoda",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "56d4eb0e92514134020120bb",
          "department": "Lighting",
          "job": "Electrician"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1596321,
          "known_for_department": "Sound",
          "name": "Matthew C. Beville",
          "original_name": "Matthew C. Beville",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc12f19251412bb30180cd",
          "department": "Sound",
          "job": "Sound Recordist"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1608789,
          "known_for_department": "Production",
          "name": "Haley Sweet",
          "original_name": "Haley Sweet",
          "popularity": 2.776,
          "profile_path": "/zhixZu8pvWH3chgQifOW98gerup.jpg",
          "credit_id": "5cc5f3289251415d3bf4df1c",
          "department": "Production",
          "job": "Location Assistant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1646284,
          "known_for_department": "Sound",
          "name": "Larry Scharf",
          "original_name": "Larry Scharf",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "59cc1436c3a368776101915e",
          "department": "Sound",
          "job": "Boom Operator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1718116,
          "known_for_department": "Lighting",
          "name": "Marc Meisenheimer",
          "original_name": "Marc Meisenheimer",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc13db9251412be10174ed",
          "department": "Lighting",
          "job": "Rigging Gaffer"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1804961,
          "known_for_department": "Production",
          "name": "Kelly Kiernan",
          "original_name": "Kelly Kiernan",
          "popularity": 0.694,
          "profile_path": null,
          "credit_id": "5cc5f2009251415cd2f98f56",
          "department": "Directing",
          "job": "Second Assistant Director"
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1804966,
          "known_for_department": "Production",
          "name": "Anna-Lisa Nilsson",
          "original_name": "Anna-Lisa Nilsson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc141cc3a368773d01a9fd",
          "department": "Production",
          "job": "Production Coordinator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1877165,
          "known_for_department": "Sound",
          "name": "Judee Flick",
          "original_name": "Judee Flick",
          "popularity": 2.188,
          "profile_path": null,
          "credit_id": "5cc5f29cc3a36820b584317d",
          "department": "Sound",
          "job": "Supervising ADR Editor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1877352,
          "known_for_department": "Art",
          "name": "Marc Gillson",
          "original_name": "Marc Gillson",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc0f9c9251412bb3017b0f",
          "department": "Art",
          "job": "Lead Painter"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1877360,
          "known_for_department": "Crew",
          "name": "Derek Hurd",
          "original_name": "Derek Hurd",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "59cc120bc3a368776e01930c",
          "department": "Crew",
          "job": "Craft Service"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1877361,
          "known_for_department": "Crew",
          "name": "Ben Parker",
          "original_name": "Ben Parker",
          "popularity": 0.728,
          "profile_path": null,
          "credit_id": "59cc126a9251412be1017231",
          "department": "Crew",
          "job": "Post Production Assistant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1878556,
          "known_for_department": "Costume & Make-Up",
          "name": "Iain Jones",
          "original_name": "Iain Jones",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "59cc12dbc3a3687761018ec0",
          "department": "Crew",
          "job": "Set Production Assistant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1878556,
          "known_for_department": "Costume & Make-Up",
          "name": "Iain Jones",
          "original_name": "Iain Jones",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "59cc11b9c3a36877a9017bd6",
          "department": "Costume & Make-Up",
          "job": "Hair Designer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895853,
          "known_for_department": "Art",
          "name": "Giuseppe Maini III",
          "original_name": "Giuseppe Maini III",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "59cc0fd89251412b8b0193e0",
          "department": "Art",
          "job": "Painter"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1895856,
          "known_for_department": "Camera",
          "name": "Mark Shane Davis",
          "original_name": "Mark Shane Davis",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "59cc11649251412bcd017f22",
          "department": "Camera",
          "job": "Key Grip"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895857,
          "known_for_department": "Camera",
          "name": "Chris Ahern",
          "original_name": "Chris Ahern",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc1170c3a368773d01a410",
          "department": "Camera",
          "job": "Grip"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895858,
          "known_for_department": "Costume & Make-Up",
          "name": "Joseph W. Grafmuller",
          "original_name": "Joseph W. Grafmuller",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc11e4c3a3687797019d40",
          "department": "Costume & Make-Up",
          "job": "Set Dressing Artist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895859,
          "known_for_department": "Crew",
          "name": "Gary L. Brennan",
          "original_name": "Gary L. Brennan",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc11f4c3a368773d01a53b",
          "department": "Crew",
          "job": "Carpenter"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895860,
          "known_for_department": "Crew",
          "name": "Alonzo Brown Jr.",
          "original_name": "Alonzo Brown Jr.",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc12239251412b8b0197fe",
          "department": "Crew",
          "job": "Driver"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895861,
          "known_for_department": "Crew",
          "name": "Angelo de la Cruz",
          "original_name": "Angelo de la Cruz",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "5cc5f2d992514120dbf410b1",
          "department": "Camera",
          "job": "Camera Loader"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895863,
          "known_for_department": "Crew",
          "name": "Ruben Cortez",
          "original_name": "Ruben Cortez",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "59cc12abc3a368774e0155ef",
          "department": "Crew",
          "job": "Security"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1895865,
          "known_for_department": "Directing",
          "name": "Francis R. Mahony III",
          "original_name": "Francis R. Mahony III",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "59cc137ec3a368770e016586",
          "department": "Directing",
          "job": "First Assistant Director"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895867,
          "known_for_department": "Lighting",
          "name": "Anthony Hall",
          "original_name": "Anthony Hall",
          "popularity": 1.164,
          "profile_path": null,
          "credit_id": "59cc13cb9251412be10174c9",
          "department": "Lighting",
          "job": "Best Boy Electric"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1895869,
          "known_for_department": "Lighting",
          "name": "Michael Stocks",
          "original_name": "Michael Stocks",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5cc5f38ac3a368467781cb96",
          "department": "Lighting",
          "job": "Key Rigging Grip"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2022847,
          "known_for_department": "Sound",
          "name": "Kristen Becht",
          "original_name": "Kristen Becht",
          "popularity": 1.048,
          "profile_path": null,
          "credit_id": "5ad25c449251417370014a4d",
          "department": "Sound",
          "job": "Assistant Music Supervisor"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2022851,
          "known_for_department": "Crew",
          "name": "Rory Dauson",
          "original_name": "Rory Dauson",
          "popularity": 1.579,
          "profile_path": null,
          "credit_id": "5ad25d170e0a266c2e015c6a",
          "department": "Crew",
          "job": "Stand In"
        },
        {
          "adult": false,
          "gender": 2,
          "id": 2057031,
          "known_for_department": "Sound",
          "name": "Jeff Courtie",
          "original_name": "Jeff Courtie",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f250c3a368282081d34c",
          "department": "Sound",
          "job": "ADR Mixer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2117623,
          "known_for_department": "Crew",
          "name": "Kevin McTurk",
          "original_name": "Kevin McTurk",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5cc5f2aec3a368282081d3c6",
          "department": "Crew",
          "job": "Special Effects Assistant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2165008,
          "known_for_department": "Production",
          "name": "Zane",
          "original_name": "Zane",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f3590e0a264eefec6c4b",
          "department": "Production",
          "job": "Assistant Accountant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2234809,
          "known_for_department": "Art",
          "name": "Chris Cullen",
          "original_name": "Chris Cullen",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f237c3a368493681eb96",
          "department": "Art",
          "job": "Graphic Designer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2247967,
          "known_for_department": "Directing",
          "name": "Bradley Morris",
          "original_name": "Bradley Morris",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f396c3a36809ab8bfc21",
          "department": "Production",
          "job": "Production Secretary"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2278016,
          "known_for_department": "Camera",
          "name": "Gregory C. Smith",
          "original_name": "Gregory C. Smith",
          "popularity": 1.051,
          "profile_path": null,
          "credit_id": "5cc5f2ef9251412ba1fbf36e",
          "department": "Camera",
          "job": "Second Assistant Camera"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299196,
          "known_for_department": "Costume & Make-Up",
          "name": "Kristin Dangl",
          "original_name": "Kristin Dangl",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "5cc5f1f4c3a3683ad581db45",
          "department": "Costume & Make-Up",
          "job": "Costumer"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299197,
          "known_for_department": "Directing",
          "name": "John W. Hyde Jr.",
          "original_name": "John W. Hyde Jr.",
          "popularity": 1.684,
          "profile_path": null,
          "credit_id": "5cc5f2109251415cd2f98f8d",
          "department": "Directing",
          "job": "Second Second Assistant Director"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299198,
          "known_for_department": "Art",
          "name": "Liz Chiz",
          "original_name": "Liz Chiz",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "5cc5f21ec3a368467781c979",
          "department": "Art",
          "job": "Assistant Decorator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299199,
          "known_for_department": "Art",
          "name": "John Felgate",
          "original_name": "John Felgate",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5cc5f22c92514120dbf40f25",
          "department": "Art",
          "job": "Assistant Property Master"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299200,
          "known_for_department": "Art",
          "name": "Steve Ingrassia",
          "original_name": "Steve Ingrassia",
          "popularity": 0.98,
          "profile_path": null,
          "credit_id": "5cc5f2469251415d3ef4da23",
          "department": "Art",
          "job": "Swing"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299203,
          "known_for_department": "Camera",
          "name": "Robbie Meckler",
          "original_name": "Robbie Meckler",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "5cc5f2cc0e0a2678a0ee296c",
          "department": "Camera",
          "job": "Best Boy Grip"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299204,
          "known_for_department": "Camera",
          "name": "Alan Parr",
          "original_name": "Alan Parr",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f2e30e0a263743ed2974",
          "department": "Camera",
          "job": "Dolly Grip"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299207,
          "known_for_department": "Production",
          "name": "Kara Mazzola",
          "original_name": "Kara Mazzola",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f3050e0a264eefec6bae",
          "department": "Production",
          "job": "Post Production Coordinator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299209,
          "known_for_department": "Sound",
          "name": "Chuck Kelley",
          "original_name": "Chuck Kelley",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f33492514120dbf41187",
          "department": "Sound",
          "job": "Music Consultant"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299211,
          "known_for_department": "Crew",
          "name": "Michael Haddad",
          "original_name": "Michael Haddad",
          "popularity": 0.6,
          "profile_path": null,
          "credit_id": "5cc5f3660e0a264eefec6c67",
          "department": "Crew",
          "job": "Assistant Craft Service"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299214,
          "known_for_department": "Production",
          "name": "Cheryl Cain",
          "original_name": "Cheryl Cain",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "5cc5f3720e0a2678a0ee2b03",
          "department": "Production",
          "job": "Assistant Production Coordinator"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2299215,
          "known_for_department": "Crew",
          "name": "Chris L. Winslow",
          "original_name": "Chris L. Winslow",
          "popularity": 1.38,
          "profile_path": null,
          "credit_id": "5cc5f37d92514119e5f40371",
          "department": "Crew",
          "job": "Charge Scenic Artist"
        },
        {
          "adult": false,
          "gender": 0,
          "id": 3182011,
          "known_for_department": "Crew",
          "name": "Andrew Ambrose",
          "original_name": "Andrew Ambrose",
          "popularity": 1.4,
          "profile_path": null,
          "credit_id": "6105c2288d22fc0076b9a6f1",
          "department": "Crew",
          "job": "Special Effects Assistant"
        }
      ]
    };
    MovieCreditsResponse movieCreditsResponse=MovieCreditsResponse.fromJson(movieCreditsResposneJson);
    return Scaffold(
      body: Center(
        child: Text(movieCreditsResponse.crew.length.toString(),style: const TextStyle(fontSize: 30),
        ),
      )
    );
  }
}

